"""
AgentsSessions resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status
from .._pagination import PaginatedIterator, AsyncPaginatedIterator
from .._streaming import SSEIterator, AsyncSSEIterator
from typing import BinaryIO


class AgentsSessionsResource:
    """Create, manage, and chat with agent sessions"""

    def __init__(self, http: HttpClient):
        self._http = http

    def create_by_name(self, name: str, body: Optional[Union["CreateSessionRequest", None]] = None) -> "CreateSessionResponse":
        """
        Create Session By Name
        
        Start a session against the latest published version of an agent by name.
        
        Resolves the current latest published version at runtime — callers do not
        need to track a specific agent ID or version. Returns 404 if no published
        version exists for the given agent name.
        
        Args:
            name: The name parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/agents/name/{name}/sessions"
        path = path.replace("{name}", str(name))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return CreateSessionResponse.model_validate(response)

    def list(self, agent_id: str, offset: Optional[int] = None, limit: Optional[Union[int, None]] = None, sort_by: Optional[str] = None, sort_order: Optional[str] = None, status: Optional[Union[str, None]] = None) -> PaginatedIterator["SessionSummary"]:
        """
        List Sessions
        
        Args:
            agent_id: The agent_id parameter
            offset: Number of items to skip
            limit: Maximum number of items to return
            sort_by: Field to sort by: start_time, status
            sort_order: Sort order: asc or desc
            status: Filter by execution status: RUNNING, COMPLETED, FAILED, CANCELED, TERMINATED
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/agents/{agent_id}/sessions"
        path = path.replace("{agent_id}", str(agent_id))
        params = {}
        if offset is not None:
            params["offset"] = offset
        if limit is not None:
            params["limit"] = limit
        if sort_by is not None:
            params["sort_by"] = sort_by
        if sort_order is not None:
            params["sort_order"] = sort_order
        if status is not None:
            params["status"] = status
        return PaginatedIterator(
            self._http,
            "GET",
            path,
            items_field="data",
            cursor_param="offset",
            next_field="next_cursor",
            params=params,
            model_class=SessionSummary,
        )

    def create(self, agent_id: str, body: Optional[Union["CreateSessionRequest", None]] = None) -> "CreateSessionResponse":
        """
        Create Session
        
        Args:
            agent_id: The agent_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/agents/{agent_id}/sessions"
        path = path.replace("{agent_id}", str(agent_id))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return CreateSessionResponse.model_validate(response)

    def send_chat_message(self, session_id: str, body: "ChatMessageRequest") -> "ChatMessageResponse":
        """
        Send Chat Message
        
        Args:
            session_id: The session_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/sessions/{session_id}/chat"
        path = path.replace("{session_id}", str(session_id))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return ChatMessageResponse.model_validate(response)

    def send_chat_message_stream(self, session_id: str, file: BinaryIO, file_name: str, user_message: Optional[Union[str, None]] = None, timeout_seconds: Optional[Union[int, None]] = None, include_thinking: Optional[Union[bool, None]] = None, include_tool_activity: Optional[Union[bool, None]] = None, files: Optional[Union[List[str], None]] = None) -> SSEIterator:
        """
        Send a chat message with file attachments and stream the response via SSE
        
        Args:
            session_id: The session_id parameter
            body: Request body
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/sessions/{session_id}/chat/stream"
        path = path.replace("{session_id}", str(session_id))
        form_fields = {}
        if user_message is not None:
            form_fields["user_message"] = str(user_message)
        if timeout_seconds is not None:
            form_fields["timeout_seconds"] = str(timeout_seconds)
        if include_thinking is not None:
            form_fields["include_thinking"] = str(include_thinking)
        if include_tool_activity is not None:
            form_fields["include_tool_activity"] = str(include_tool_activity)
        if files is not None:
            form_fields["files"] = str(files)
        return self._http.upload_stream("POST", path, file=file, file_name=file_name, field_name="file", form_fields=form_fields)


class AsyncAgentsSessionsResource:
    """Create, manage, and chat with agent sessions (async)"""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def create_by_name(self, name: str, body: Optional[Union["CreateSessionRequest", None]] = None) -> "CreateSessionResponse":
        """
        Create Session By Name
        
        Start a session against the latest published version of an agent by name.
        
        Resolves the current latest published version at runtime — callers do not
        need to track a specific agent ID or version. Returns 404 if no published
        version exists for the given agent name.
        
        Args:
            name: The name parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/agents/name/{name}/sessions"
        path = path.replace("{name}", str(name))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return CreateSessionResponse.model_validate(response)

    async def list(self, agent_id: str, offset: Optional[int] = None, limit: Optional[Union[int, None]] = None, sort_by: Optional[str] = None, sort_order: Optional[str] = None, status: Optional[Union[str, None]] = None) -> AsyncPaginatedIterator["SessionSummary"]:
        """
        List Sessions
        
        Args:
            agent_id: The agent_id parameter
            offset: Number of items to skip
            limit: Maximum number of items to return
            sort_by: Field to sort by: start_time, status
            sort_order: Sort order: asc or desc
            status: Filter by execution status: RUNNING, COMPLETED, FAILED, CANCELED, TERMINATED
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/agents/{agent_id}/sessions"
        path = path.replace("{agent_id}", str(agent_id))
        params = {}
        if offset is not None:
            params["offset"] = offset
        if limit is not None:
            params["limit"] = limit
        if sort_by is not None:
            params["sort_by"] = sort_by
        if sort_order is not None:
            params["sort_order"] = sort_order
        if status is not None:
            params["status"] = status
        return AsyncPaginatedIterator(
            self._http,
            "GET",
            path,
            items_field="data",
            cursor_param="offset",
            next_field="next_cursor",
            params=params,
            model_class=SessionSummary,
        )

    async def create(self, agent_id: str, body: Optional[Union["CreateSessionRequest", None]] = None) -> "CreateSessionResponse":
        """
        Create Session
        
        Args:
            agent_id: The agent_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/agents/{agent_id}/sessions"
        path = path.replace("{agent_id}", str(agent_id))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return CreateSessionResponse.model_validate(response)

    async def send_chat_message(self, session_id: str, body: "ChatMessageRequest") -> "ChatMessageResponse":
        """
        Send Chat Message
        
        Args:
            session_id: The session_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/sessions/{session_id}/chat"
        path = path.replace("{session_id}", str(session_id))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return ChatMessageResponse.model_validate(response)

    async def send_chat_message_stream(self, session_id: str, file: BinaryIO, file_name: str, user_message: Optional[Union[str, None]] = None, timeout_seconds: Optional[Union[int, None]] = None, include_thinking: Optional[Union[bool, None]] = None, include_tool_activity: Optional[Union[bool, None]] = None, files: Optional[Union[List[str], None]] = None) -> AsyncSSEIterator:
        """
        Send a chat message with file attachments and stream the response via SSE
        
        Args:
            session_id: The session_id parameter
            body: Request body
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/sessions/{session_id}/chat/stream"
        path = path.replace("{session_id}", str(session_id))
        form_fields = {}
        if user_message is not None:
            form_fields["user_message"] = str(user_message)
        if timeout_seconds is not None:
            form_fields["timeout_seconds"] = str(timeout_seconds)
        if include_thinking is not None:
            form_fields["include_thinking"] = str(include_thinking)
        if include_tool_activity is not None:
            form_fields["include_tool_activity"] = str(include_tool_activity)
        if files is not None:
            form_fields["files"] = str(files)
        return await self._http.upload_stream("POST", path, file=file, file_name=file_name, field_name="file", form_fields=form_fields)
