"""
AgentsSessions resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status
from .._pagination import PaginatedIterator, AsyncPaginatedIterator


class AgentsSessionsResource:
    """Manage sessions for a specific agent"""

    def __init__(self, http: HttpClient):
        self._http = http

    def list_sessions(self, agent_id: str, offset: Optional[int] = None, limit: Optional[Union[int, None]] = None, sort_by: Optional[str] = None, sort_order: Optional[str] = None, status: Optional[Union[str, None]] = None) -> PaginatedIterator["SessionSummary"]:
        """
        List Sessions
        
        Args:
            agent_id: The agent_id parameter
            offset: Number of items to skip
            limit: Maximum number of items to return
            sort_by: Field to sort by: start_time, status
            sort_order: Sort order: asc or desc
            status: Filter by execution status: RUNNING, COMPLETED, FAILED, CANCELED, TERMINATED
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/agents/{agent_id}/sessions"
        path = path.replace("{agent_id}", str(agent_id))
        params = {}
        if offset is not None:
            params["offset"] = offset
        if limit is not None:
            params["limit"] = limit
        if sort_by is not None:
            params["sort_by"] = sort_by
        if sort_order is not None:
            params["sort_order"] = sort_order
        if status is not None:
            params["status"] = status
        return PaginatedIterator(
            self._http,
            "GET",
            path,
            items_field="data",
            cursor_param="offset",
            next_field="next_cursor",
            params=params,
        )

    def create_session(self, agent_id: str, body: Optional[Union["CreateSessionRequest", None]] = None) -> "CreateSessionResponse":
        """
        Create Session
        
        Args:
            agent_id: The agent_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/agents/{agent_id}/sessions"
        path = path.replace("{agent_id}", str(agent_id))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return CreateSessionResponse.model_validate(response)


class AsyncAgentsSessionsResource:
    """Manage sessions for a specific agent (async)"""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def list_sessions(self, agent_id: str, offset: Optional[int] = None, limit: Optional[Union[int, None]] = None, sort_by: Optional[str] = None, sort_order: Optional[str] = None, status: Optional[Union[str, None]] = None) -> AsyncPaginatedIterator["SessionSummary"]:
        """
        List Sessions
        
        Args:
            agent_id: The agent_id parameter
            offset: Number of items to skip
            limit: Maximum number of items to return
            sort_by: Field to sort by: start_time, status
            sort_order: Sort order: asc or desc
            status: Filter by execution status: RUNNING, COMPLETED, FAILED, CANCELED, TERMINATED
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/agents/{agent_id}/sessions"
        path = path.replace("{agent_id}", str(agent_id))
        params = {}
        if offset is not None:
            params["offset"] = offset
        if limit is not None:
            params["limit"] = limit
        if sort_by is not None:
            params["sort_by"] = sort_by
        if sort_order is not None:
            params["sort_order"] = sort_order
        if status is not None:
            params["status"] = status
        return AsyncPaginatedIterator(
            self._http,
            "GET",
            path,
            items_field="data",
            cursor_param="offset",
            next_field="next_cursor",
            params=params,
        )

    async def create_session(self, agent_id: str, body: Optional[Union["CreateSessionRequest", None]] = None) -> "CreateSessionResponse":
        """
        Create Session
        
        Args:
            agent_id: The agent_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/agents/{agent_id}/sessions"
        path = path.replace("{agent_id}", str(agent_id))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return CreateSessionResponse.model_validate(response)
