"""
Batches resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status
from .executions import ExecutionsResource, AsyncExecutionsResource


class BatchesResource:
    """Create and manage batch processing definitions"""

    def __init__(self, http: HttpClient):
        self._http = http
        self.executions = ExecutionsResource(http)

    def list(self, offset: Optional[int] = None, limit: Optional[int] = None) -> "GetBatchDefinitionsResponse":
        """
        List Batch Definitions
        
        Args:
            offset: The offset parameter
            limit: The limit parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-definitions"
        params: Dict[str, Any] = {}
        if offset is not None:
            params["offset"] = offset
        if limit is not None:
            params["limit"] = limit
        response = self._http.request("GET", path, params=params)
        return GetBatchDefinitionsResponse.model_validate(response)

    def create(self, body: "CreateBatchDefinitionRequest") -> "CreateBatchDefinitionResponse":
        """
        Create Batch Definition
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-definitions"
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return CreateBatchDefinitionResponse.model_validate(response)

    def get_by_catalog_urn(self, catalog_urn: str) -> "BatchDefinitionResponse":
        """
        Get Batch Definition By Catalog Urn
        
        Args:
            catalog_urn: urn:meibel:batch-definition:{customer}:{project}:{id}
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-definitions/catalog-urn"
        params: Dict[str, Any] = {}
        if catalog_urn is not None:
            params["catalog_urn"] = catalog_urn
        response = self._http.request("GET", path, params=params)
        return BatchDefinitionResponse.model_validate(response)

    def get_by_id(self, definition_id: str) -> "BatchDefinitionResponse":
        """
        Get Batch Definition By Id
        
        Args:
            definition_id: The definition_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-definitions/id/{definition_id}"
        path = path.replace("{definition_id}", str(definition_id))
        response = self._http.request("GET", path)
        return BatchDefinitionResponse.model_validate(response)

    def update_by_id(self, definition_id: str, body: "UpdateBatchDefinitionRequest") -> "UpdateBatchDefinitionResponse":
        """
        Update Batch Definition By Id
        
        Args:
            definition_id: The definition_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-definitions/id/{definition_id}"
        path = path.replace("{definition_id}", str(definition_id))
        response = self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return UpdateBatchDefinitionResponse.model_validate(response)

    def delete_by_id(self, definition_id: str) -> None:
        """
        Delete Batch Definition By Id
        
        Args:
            definition_id: The definition_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-definitions/id/{definition_id}"
        path = path.replace("{definition_id}", str(definition_id))
        response = self._http.request("DELETE", path)
        return response

    def list_versions(self, definition_id: str, offset: Optional[int] = None, limit: Optional[Union[int, None]] = None) -> "GetBatchDefinitionsResponse":
        """
        List Batch Definition Versions
        
        Args:
            definition_id: The definition_id parameter
            offset: The offset parameter
            limit: The limit parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-definitions/id/{definition_id}/versions"
        path = path.replace("{definition_id}", str(definition_id))
        params: Dict[str, Any] = {}
        if offset is not None:
            params["offset"] = offset
        if limit is not None:
            params["limit"] = limit
        response = self._http.request("GET", path, params=params)
        return GetBatchDefinitionsResponse.model_validate(response)

    def execute(self, definition_id: str) -> "ExecuteBatchDefinitionResponse":
        """
        Execute Batch Definition
        
        Args:
            definition_id: The definition_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-definitions/id/{definition_id}/execute"
        path = path.replace("{definition_id}", str(definition_id))
        response = self._http.request("POST", path)
        return ExecuteBatchDefinitionResponse.model_validate(response)


class AsyncBatchesResource:
    """Create and manage batch processing definitions (async)"""

    def __init__(self, http: AsyncHttpClient):
        self._http = http
        self.executions = AsyncExecutionsResource(http)

    async def list(self, offset: Optional[int] = None, limit: Optional[int] = None) -> "GetBatchDefinitionsResponse":
        """
        List Batch Definitions
        
        Args:
            offset: The offset parameter
            limit: The limit parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-definitions"
        params: Dict[str, Any] = {}
        if offset is not None:
            params["offset"] = offset
        if limit is not None:
            params["limit"] = limit
        response = await self._http.request("GET", path, params=params)
        return GetBatchDefinitionsResponse.model_validate(response)

    async def create(self, body: "CreateBatchDefinitionRequest") -> "CreateBatchDefinitionResponse":
        """
        Create Batch Definition
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-definitions"
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return CreateBatchDefinitionResponse.model_validate(response)

    async def get_by_catalog_urn(self, catalog_urn: str) -> "BatchDefinitionResponse":
        """
        Get Batch Definition By Catalog Urn
        
        Args:
            catalog_urn: urn:meibel:batch-definition:{customer}:{project}:{id}
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-definitions/catalog-urn"
        params: Dict[str, Any] = {}
        if catalog_urn is not None:
            params["catalog_urn"] = catalog_urn
        response = await self._http.request("GET", path, params=params)
        return BatchDefinitionResponse.model_validate(response)

    async def get_by_id(self, definition_id: str) -> "BatchDefinitionResponse":
        """
        Get Batch Definition By Id
        
        Args:
            definition_id: The definition_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-definitions/id/{definition_id}"
        path = path.replace("{definition_id}", str(definition_id))
        response = await self._http.request("GET", path)
        return BatchDefinitionResponse.model_validate(response)

    async def update_by_id(self, definition_id: str, body: "UpdateBatchDefinitionRequest") -> "UpdateBatchDefinitionResponse":
        """
        Update Batch Definition By Id
        
        Args:
            definition_id: The definition_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-definitions/id/{definition_id}"
        path = path.replace("{definition_id}", str(definition_id))
        response = await self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return UpdateBatchDefinitionResponse.model_validate(response)

    async def delete_by_id(self, definition_id: str) -> None:
        """
        Delete Batch Definition By Id
        
        Args:
            definition_id: The definition_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-definitions/id/{definition_id}"
        path = path.replace("{definition_id}", str(definition_id))
        response = await self._http.request("DELETE", path)
        return response

    async def list_versions(self, definition_id: str, offset: Optional[int] = None, limit: Optional[Union[int, None]] = None) -> "GetBatchDefinitionsResponse":
        """
        List Batch Definition Versions
        
        Args:
            definition_id: The definition_id parameter
            offset: The offset parameter
            limit: The limit parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-definitions/id/{definition_id}/versions"
        path = path.replace("{definition_id}", str(definition_id))
        params: Dict[str, Any] = {}
        if offset is not None:
            params["offset"] = offset
        if limit is not None:
            params["limit"] = limit
        response = await self._http.request("GET", path, params=params)
        return GetBatchDefinitionsResponse.model_validate(response)

    async def execute(self, definition_id: str) -> "ExecuteBatchDefinitionResponse":
        """
        Execute Batch Definition
        
        Args:
            definition_id: The definition_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-definitions/id/{definition_id}/execute"
        path = path.replace("{definition_id}", str(definition_id))
        response = await self._http.request("POST", path)
        return ExecuteBatchDefinitionResponse.model_validate(response)
