"""
blueprints.executions resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status


class BlueprintsExecutionsResource:
    """blueprints.executions resource operations."""

    def __init__(self, http: HttpClient):
        self._http = http

    def start_blueprint_instance(self, blueprint_instance_id: str, body: Optional[Union["StartBlueprintInstanceRequest", None]] = None) -> str:
        """
        Start Blueprint Instance
        
        Args:
            blueprint_instance_id: Unique identifier for the workflow instance
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/{blueprint_instance_id}/start-instance"
        path = path.replace("{blueprint_instance_id}", str(blueprint_instance_id))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return response

    def cancel_blueprint_instance(self, blueprint_instance_id: str) -> str:
        """
        Cancel Blueprint Instance
        
        Args:
            blueprint_instance_id: Unique identifier for the workflow instance
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/{blueprint_instance_id}/cancel-instance"
        path = path.replace("{blueprint_instance_id}", str(blueprint_instance_id))
        response = self._http.request("POST", path)
        return response

    def send_signal(self, blueprint_instance_id: str, signal_name: str, body: Optional[Union[List[str], None]] = None) -> str:
        """
        Send Signal
        
        Args:
            blueprint_instance_id: Unique identifier for the workflow instance
            signal_name: Name of the signal to send
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/{blueprint_instance_id}/signals/{signal_name}"
        path = path.replace("{blueprint_instance_id}", str(blueprint_instance_id))
        path = path.replace("{signal_name}", str(signal_name))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return response

    def query_workflow(self, blueprint_instance_id: str, query_name: str, body: Optional[Union[List[str], None]] = None) -> str:
        """
        Query Workflow
        
        Args:
            blueprint_instance_id: Unique identifier for the workflow instance
            query_name: Name of the query to execute
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/{blueprint_instance_id}/queries/{query_name}"
        path = path.replace("{blueprint_instance_id}", str(blueprint_instance_id))
        path = path.replace("{query_name}", str(query_name))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return response

    def get_blueprint_instance_workflow_status(self, blueprint_instance_id: str) -> str:
        """
        Get Blueprint Instance Workflow Status
        
        Args:
            blueprint_instance_id: Unique identifier for the workflow instance
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/{blueprint_instance_id}/workflow-status"
        path = path.replace("{blueprint_instance_id}", str(blueprint_instance_id))
        response = self._http.request("GET", path)
        return response

    def send_chat_message(self, blueprint_instance_id: str, body: "ChatMessageRequest") -> "ChatMessageResponse":
        """
        Send Chat Message
        
        Args:
            blueprint_instance_id: The blueprint_instance_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/{blueprint_instance_id}/chat"
        path = path.replace("{blueprint_instance_id}", str(blueprint_instance_id))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return ChatMessageResponse.model_validate(response)

    def send_chat_message_stream(self, blueprint_instance_id: str, body: "ChatMessageRequest") -> None:
        """
        Send a chat message and stream the response via SSE
        
        Send a chat message to a running chat agent workflow and stream the response as Server-Sent Events.
        
        Args:
            blueprint_instance_id: The blueprint_instance_id parameter
            body: Request body
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/{blueprint_instance_id}/chat/stream"
        path = path.replace("{blueprint_instance_id}", str(blueprint_instance_id))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return response


class AsyncBlueprintsExecutionsResource:
    """blueprints.executions resource operations (async)."""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def start_blueprint_instance(self, blueprint_instance_id: str, body: Optional[Union["StartBlueprintInstanceRequest", None]] = None) -> str:
        """
        Start Blueprint Instance
        
        Args:
            blueprint_instance_id: Unique identifier for the workflow instance
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/{blueprint_instance_id}/start-instance"
        path = path.replace("{blueprint_instance_id}", str(blueprint_instance_id))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return response

    async def cancel_blueprint_instance(self, blueprint_instance_id: str) -> str:
        """
        Cancel Blueprint Instance
        
        Args:
            blueprint_instance_id: Unique identifier for the workflow instance
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/{blueprint_instance_id}/cancel-instance"
        path = path.replace("{blueprint_instance_id}", str(blueprint_instance_id))
        response = await self._http.request("POST", path)
        return response

    async def send_signal(self, blueprint_instance_id: str, signal_name: str, body: Optional[Union[List[str], None]] = None) -> str:
        """
        Send Signal
        
        Args:
            blueprint_instance_id: Unique identifier for the workflow instance
            signal_name: Name of the signal to send
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/{blueprint_instance_id}/signals/{signal_name}"
        path = path.replace("{blueprint_instance_id}", str(blueprint_instance_id))
        path = path.replace("{signal_name}", str(signal_name))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return response

    async def query_workflow(self, blueprint_instance_id: str, query_name: str, body: Optional[Union[List[str], None]] = None) -> str:
        """
        Query Workflow
        
        Args:
            blueprint_instance_id: Unique identifier for the workflow instance
            query_name: Name of the query to execute
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/{blueprint_instance_id}/queries/{query_name}"
        path = path.replace("{blueprint_instance_id}", str(blueprint_instance_id))
        path = path.replace("{query_name}", str(query_name))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return response

    async def get_blueprint_instance_workflow_status(self, blueprint_instance_id: str) -> str:
        """
        Get Blueprint Instance Workflow Status
        
        Args:
            blueprint_instance_id: Unique identifier for the workflow instance
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/{blueprint_instance_id}/workflow-status"
        path = path.replace("{blueprint_instance_id}", str(blueprint_instance_id))
        response = await self._http.request("GET", path)
        return response

    async def send_chat_message(self, blueprint_instance_id: str, body: "ChatMessageRequest") -> "ChatMessageResponse":
        """
        Send Chat Message
        
        Args:
            blueprint_instance_id: The blueprint_instance_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/{blueprint_instance_id}/chat"
        path = path.replace("{blueprint_instance_id}", str(blueprint_instance_id))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return ChatMessageResponse.model_validate(response)

    async def send_chat_message_stream(self, blueprint_instance_id: str, body: "ChatMessageRequest") -> None:
        """
        Send a chat message and stream the response via SSE
        
        Send a chat message to a running chat agent workflow and stream the response as Server-Sent Events.
        
        Args:
            blueprint_instance_id: The blueprint_instance_id parameter
            body: Request body
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/{blueprint_instance_id}/chat/stream"
        path = path.replace("{blueprint_instance_id}", str(blueprint_instance_id))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return response
