"""
ConfidenceScoring resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status


class ConfidenceScoringResource:
    """Track and analyze confidence scores"""

    def __init__(self, http: HttpClient):
        self._http = http

    def get_scoring_job(self, job_id: str) -> "ScoringJobRecord":
        """
        Get a scoring job
        
        Retrieve a single confidence scoring job by its ID, including its current status and score if completed.
        
        Args:
            job_id: Unique identifier of the scoring job to retrieve.
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/confidence-scoring/job/{job_id}"
        path = path.replace("{job_id}", str(job_id))
        response = self._http.request("GET", path)
        return ScoringJobRecord.model_validate(response)

    def list_scoring_jobs(self, agent_name: Optional[Union[str, None]] = None, agent_version: Optional[Union[str, None]] = None, agent_session_id: Optional[Union[str, None]] = None, agent_workflow_name: Optional[Union[str, None]] = None, agent_workflow_version: Optional[Union[str, None]] = None, agent_workflow_session_id: Optional[Union[str, None]] = None, tool_id: Optional[Union[str, None]] = None, tool_instance_id: Optional[Union[str, None]] = None, tool_execution_id: Optional[Union[str, None]] = None) -> List["ScoringJobRecord"]:
        """
        List scoring jobs
        
        List confidence scoring jobs, optionally filtered by identity context fields. All filters are combined with AND logic.
        
        Args:
            agent_name: Filter by agent name.
            agent_version: Filter by agent version.
            agent_session_id: Filter by agent session ID.
            agent_workflow_name: Filter by workflow name.
            agent_workflow_version: Filter by workflow version.
            agent_workflow_session_id: Filter by workflow session ID.
            tool_id: Filter by tool identifier.
            tool_instance_id: Filter by tool instance identifier.
            tool_execution_id: Filter by tool execution identifier.
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/confidence-scoring/jobs"
        params = {}
        if agent_name is not None:
            params["agent_name"] = agent_name
        if agent_version is not None:
            params["agent_version"] = agent_version
        if agent_session_id is not None:
            params["agent_session_id"] = agent_session_id
        if agent_workflow_name is not None:
            params["agent_workflow_name"] = agent_workflow_name
        if agent_workflow_version is not None:
            params["agent_workflow_version"] = agent_workflow_version
        if agent_workflow_session_id is not None:
            params["agent_workflow_session_id"] = agent_workflow_session_id
        if tool_id is not None:
            params["tool_id"] = tool_id
        if tool_instance_id is not None:
            params["tool_instance_id"] = tool_instance_id
        if tool_execution_id is not None:
            params["tool_execution_id"] = tool_execution_id
        response = self._http.request("GET", path, params=params)
        return [ScoringJobRecord.model_validate(item) for item in response]

    def get_scoring_jobs_summary(self, primary: str, secondary: Optional[Union[str, None]] = None) -> "ScoreSummary":
        """
        Get scoring summary
        
        Get an aggregated summary of confidence scores. Requires a primary filter; an optional secondary filter narrows results further. Filters use the format "field:value", where field is any identity context field name.
        
        Args:
            primary: Primary filter in "field:value" format, where field is an identity context field name (e.g. "agent_name:my-agent" or "agent_session_id:sess_abc123").
            secondary: Optional secondary filter in the same "field:value" format to further narrow results (e.g. "agent_version:1.2.0").
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/confidence-scoring/summary"
        params = {}
        if primary is not None:
            params["primary"] = primary
        if secondary is not None:
            params["secondary"] = secondary
        response = self._http.request("GET", path, params=params)
        return ScoreSummary.model_validate(response)


class AsyncConfidenceScoringResource:
    """Track and analyze confidence scores (async)"""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def get_scoring_job(self, job_id: str) -> "ScoringJobRecord":
        """
        Get a scoring job
        
        Retrieve a single confidence scoring job by its ID, including its current status and score if completed.
        
        Args:
            job_id: Unique identifier of the scoring job to retrieve.
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/confidence-scoring/job/{job_id}"
        path = path.replace("{job_id}", str(job_id))
        response = await self._http.request("GET", path)
        return ScoringJobRecord.model_validate(response)

    async def list_scoring_jobs(self, agent_name: Optional[Union[str, None]] = None, agent_version: Optional[Union[str, None]] = None, agent_session_id: Optional[Union[str, None]] = None, agent_workflow_name: Optional[Union[str, None]] = None, agent_workflow_version: Optional[Union[str, None]] = None, agent_workflow_session_id: Optional[Union[str, None]] = None, tool_id: Optional[Union[str, None]] = None, tool_instance_id: Optional[Union[str, None]] = None, tool_execution_id: Optional[Union[str, None]] = None) -> List["ScoringJobRecord"]:
        """
        List scoring jobs
        
        List confidence scoring jobs, optionally filtered by identity context fields. All filters are combined with AND logic.
        
        Args:
            agent_name: Filter by agent name.
            agent_version: Filter by agent version.
            agent_session_id: Filter by agent session ID.
            agent_workflow_name: Filter by workflow name.
            agent_workflow_version: Filter by workflow version.
            agent_workflow_session_id: Filter by workflow session ID.
            tool_id: Filter by tool identifier.
            tool_instance_id: Filter by tool instance identifier.
            tool_execution_id: Filter by tool execution identifier.
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/confidence-scoring/jobs"
        params = {}
        if agent_name is not None:
            params["agent_name"] = agent_name
        if agent_version is not None:
            params["agent_version"] = agent_version
        if agent_session_id is not None:
            params["agent_session_id"] = agent_session_id
        if agent_workflow_name is not None:
            params["agent_workflow_name"] = agent_workflow_name
        if agent_workflow_version is not None:
            params["agent_workflow_version"] = agent_workflow_version
        if agent_workflow_session_id is not None:
            params["agent_workflow_session_id"] = agent_workflow_session_id
        if tool_id is not None:
            params["tool_id"] = tool_id
        if tool_instance_id is not None:
            params["tool_instance_id"] = tool_instance_id
        if tool_execution_id is not None:
            params["tool_execution_id"] = tool_execution_id
        response = await self._http.request("GET", path, params=params)
        return [ScoringJobRecord.model_validate(item) for item in response]

    async def get_scoring_jobs_summary(self, primary: str, secondary: Optional[Union[str, None]] = None) -> "ScoreSummary":
        """
        Get scoring summary
        
        Get an aggregated summary of confidence scores. Requires a primary filter; an optional secondary filter narrows results further. Filters use the format "field:value", where field is any identity context field name.
        
        Args:
            primary: Primary filter in "field:value" format, where field is an identity context field name (e.g. "agent_name:my-agent" or "agent_session_id:sess_abc123").
            secondary: Optional secondary filter in the same "field:value" format to further narrow results (e.g. "agent_version:1.2.0").
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/confidence-scoring/summary"
        params = {}
        if primary is not None:
            params["primary"] = primary
        if secondary is not None:
            params["secondary"] = secondary
        response = await self._http.request("GET", path, params=params)
        return ScoreSummary.model_validate(response)
