"""
Confidence Scoring resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status
from .._pagination import PaginatedIterator, AsyncPaginatedIterator


class ConfidenceScoringResource:
    """Confidence Scoring resource operations."""

    def __init__(self, http: HttpClient):
        self._http = http

    def get_scoring_job(self, job_id: str) -> str:
        """
        Get Scoring Job
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/confidence-scoring/job/{job_id}"
        path = path.replace("{job_id}", str(job_id))
        response = self._http.request("GET", path)
        return response

    def list_scoring_jobs(self, agent_name: Optional[Union[str, None]] = None, agent_version: Optional[Union[str, None]] = None, agent_execution_id: Optional[Union[str, None]] = None, agent_workflow_name: Optional[Union[str, None]] = None, agent_workflow_version: Optional[Union[str, None]] = None, agent_workflow_execution_id: Optional[Union[str, None]] = None, tool_id: Optional[Union[str, None]] = None, tool_instance_id: Optional[Union[str, None]] = None, tool_execution_id: Optional[Union[str, None]] = None) -> PaginatedIterator[str]:
        """
        List Scoring Jobs
        
        Args:
            agent_name: The agent_name parameter
            agent_version: The agent_version parameter
            agent_execution_id: The agent_execution_id parameter
            agent_workflow_name: The agent_workflow_name parameter
            agent_workflow_version: The agent_workflow_version parameter
            agent_workflow_execution_id: The agent_workflow_execution_id parameter
            tool_id: The tool_id parameter
            tool_instance_id: The tool_instance_id parameter
            tool_execution_id: The tool_execution_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/confidence-scoring/jobs"
        params = {}
        if agent_name is not None:
            params["agent_name"] = agent_name
        if agent_version is not None:
            params["agent_version"] = agent_version
        if agent_execution_id is not None:
            params["agent_execution_id"] = agent_execution_id
        if agent_workflow_name is not None:
            params["agent_workflow_name"] = agent_workflow_name
        if agent_workflow_version is not None:
            params["agent_workflow_version"] = agent_workflow_version
        if agent_workflow_execution_id is not None:
            params["agent_workflow_execution_id"] = agent_workflow_execution_id
        if tool_id is not None:
            params["tool_id"] = tool_id
        if tool_instance_id is not None:
            params["tool_instance_id"] = tool_instance_id
        if tool_execution_id is not None:
            params["tool_execution_id"] = tool_execution_id
        return PaginatedIterator(
            self._http,
            "GET",
            path,
            items_field="items",
            cursor_param="offset",
            next_field="next_cursor",
            params=params,
        )

    def get_scoring_jobs_summary(self, primary: str, secondary: Optional[Union[str, None]] = None) -> "ScoreSummary":
        """
        Get Scoring Jobs Summary
        
        Args:
            primary: The primary parameter
            secondary: The secondary parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/confidence-scoring/summary"
        params = {}
        if primary is not None:
            params["primary"] = primary
        if secondary is not None:
            params["secondary"] = secondary
        response = self._http.request("GET", path, params=params)
        return ScoreSummary.model_validate(response)


class AsyncConfidenceScoringResource:
    """Confidence Scoring resource operations (async)."""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def get_scoring_job(self, job_id: str) -> str:
        """
        Get Scoring Job
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/confidence-scoring/job/{job_id}"
        path = path.replace("{job_id}", str(job_id))
        response = await self._http.request("GET", path)
        return response

    async def list_scoring_jobs(self, agent_name: Optional[Union[str, None]] = None, agent_version: Optional[Union[str, None]] = None, agent_execution_id: Optional[Union[str, None]] = None, agent_workflow_name: Optional[Union[str, None]] = None, agent_workflow_version: Optional[Union[str, None]] = None, agent_workflow_execution_id: Optional[Union[str, None]] = None, tool_id: Optional[Union[str, None]] = None, tool_instance_id: Optional[Union[str, None]] = None, tool_execution_id: Optional[Union[str, None]] = None) -> AsyncPaginatedIterator[str]:
        """
        List Scoring Jobs
        
        Args:
            agent_name: The agent_name parameter
            agent_version: The agent_version parameter
            agent_execution_id: The agent_execution_id parameter
            agent_workflow_name: The agent_workflow_name parameter
            agent_workflow_version: The agent_workflow_version parameter
            agent_workflow_execution_id: The agent_workflow_execution_id parameter
            tool_id: The tool_id parameter
            tool_instance_id: The tool_instance_id parameter
            tool_execution_id: The tool_execution_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/confidence-scoring/jobs"
        params = {}
        if agent_name is not None:
            params["agent_name"] = agent_name
        if agent_version is not None:
            params["agent_version"] = agent_version
        if agent_execution_id is not None:
            params["agent_execution_id"] = agent_execution_id
        if agent_workflow_name is not None:
            params["agent_workflow_name"] = agent_workflow_name
        if agent_workflow_version is not None:
            params["agent_workflow_version"] = agent_workflow_version
        if agent_workflow_execution_id is not None:
            params["agent_workflow_execution_id"] = agent_workflow_execution_id
        if tool_id is not None:
            params["tool_id"] = tool_id
        if tool_instance_id is not None:
            params["tool_instance_id"] = tool_instance_id
        if tool_execution_id is not None:
            params["tool_execution_id"] = tool_execution_id
        return AsyncPaginatedIterator(
            self._http,
            "GET",
            path,
            items_field="items",
            cursor_param="offset",
            next_field="next_cursor",
            params=params,
        )

    async def get_scoring_jobs_summary(self, primary: str, secondary: Optional[Union[str, None]] = None) -> "ScoreSummary":
        """
        Get Scoring Jobs Summary
        
        Args:
            primary: The primary parameter
            secondary: The secondary parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/confidence-scoring/summary"
        params = {}
        if primary is not None:
            params["primary"] = primary
        if secondary is not None:
            params["secondary"] = secondary
        response = await self._http.request("GET", path, params=params)
        return ScoreSummary.model_validate(response)
