"""
Content resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status
from typing import BinaryIO


class ContentResource:
    """Upload, manage, and ingest content files"""

    def __init__(self, http: HttpClient):
        self._http = http

    def stream_upload_progress(self, upload_id: str) -> None:
        """
        Stream upload progress events
        
        Subscribe to real-time upload progress updates via Server-Sent Events
        
        Args:
            upload_id: The upload_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/uploads/{upload_id}/progress"
        path = path.replace("{upload_id}", str(upload_id))
        response = self._http.request("GET", path)
        return response

    def trigger_ingest(self, datasource_id: str) -> str:
        """
        Trigger ingest
        
        Trigger ingestion for a datasource
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/trigger-ingest"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("GET", path)
        return response

    def list_content(self, datasource_id: str, prefix: Optional[Union[str, None]] = None, continuation_token: Optional[Union[str, None]] = None, limit: Optional[int] = None) -> str:
        """
        List Content
        
        Args:
            datasource_id: The datasource_id parameter
            prefix: Filter content by path prefix
            continuation_token: Token for pagination
            limit: Maximum items to return
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/datasources/{datasource_id}/content"
        path = path.replace("{datasource_id}", str(datasource_id))
        params = {}
        if prefix is not None:
            params["prefix"] = prefix
        if continuation_token is not None:
            params["continuation_token"] = continuation_token
        if limit is not None:
            params["limit"] = limit
        response = self._http.request("GET", path, params=params)
        return response

    def upload_content(self, datasource_id: str, file: BinaryIO, file_name: str) -> str:
        """
        Upload Content
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/datasources/{datasource_id}/content"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.upload("POST", path, file=file, file_name=file_name)
        return response

    def stream_upload_progress(self, upload_id: str) -> None:
        """
        Stream Upload Progress
        
        Args:
            upload_id: The upload_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/uploads/{upload_id}/progress"
        path = path.replace("{upload_id}", str(upload_id))
        response = self._http.request("GET", path)
        return response

    def trigger_ingest(self, datasource_id: str) -> str:
        """
        Trigger Ingest
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/datasources/{datasource_id}/trigger-ingest"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("POST", path)
        return response


class AsyncContentResource:
    """Upload, manage, and ingest content files (async)"""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def stream_upload_progress(self, upload_id: str) -> None:
        """
        Stream upload progress events
        
        Subscribe to real-time upload progress updates via Server-Sent Events
        
        Args:
            upload_id: The upload_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/uploads/{upload_id}/progress"
        path = path.replace("{upload_id}", str(upload_id))
        response = await self._http.request("GET", path)
        return response

    async def trigger_ingest(self, datasource_id: str) -> str:
        """
        Trigger ingest
        
        Trigger ingestion for a datasource
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/trigger-ingest"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("GET", path)
        return response

    async def list_content(self, datasource_id: str, prefix: Optional[Union[str, None]] = None, continuation_token: Optional[Union[str, None]] = None, limit: Optional[int] = None) -> str:
        """
        List Content
        
        Args:
            datasource_id: The datasource_id parameter
            prefix: Filter content by path prefix
            continuation_token: Token for pagination
            limit: Maximum items to return
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/datasources/{datasource_id}/content"
        path = path.replace("{datasource_id}", str(datasource_id))
        params = {}
        if prefix is not None:
            params["prefix"] = prefix
        if continuation_token is not None:
            params["continuation_token"] = continuation_token
        if limit is not None:
            params["limit"] = limit
        response = await self._http.request("GET", path, params=params)
        return response

    async def upload_content(self, datasource_id: str, file: BinaryIO, file_name: str) -> str:
        """
        Upload Content
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/datasources/{datasource_id}/content"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.upload("POST", path, file=file, file_name=file_name)
        return response

    async def stream_upload_progress(self, upload_id: str) -> None:
        """
        Stream Upload Progress
        
        Args:
            upload_id: The upload_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/uploads/{upload_id}/progress"
        path = path.replace("{upload_id}", str(upload_id))
        response = await self._http.request("GET", path)
        return response

    async def trigger_ingest(self, datasource_id: str) -> str:
        """
        Trigger Ingest
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/datasources/{datasource_id}/trigger-ingest"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("POST", path)
        return response
