"""
Datasources resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status
from .._pagination import PaginatedIterator, AsyncPaginatedIterator


class DatasourcesResource:
    """Datasources resource operations."""

    def __init__(self, http: HttpClient):
        self._http = http

    def list_datasources(self) -> PaginatedIterator["DatasourceResponse"]:
        """
        List Datasources
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources"
        return PaginatedIterator(
            self._http,
            "GET",
            path,
            items_field="datasources",
            cursor_param="offset",
            next_field="next_cursor",
        )

    def create_datasource(self, body: "CreateDatasourceRequest") -> "DatasourceResponse":
        """
        Create Datasource
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources"
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return DatasourceResponse.model_validate(response)

    def get_datasource(self, datasource_id: str) -> "DatasourceResponse":
        """
        Get Datasource
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("GET", path)
        return DatasourceResponse.model_validate(response)

    def update_datasource(self, datasource_id: str, body: "UpdateDatasourceRequest") -> "DatasourceResponse":
        """
        Update Datasource
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return DatasourceResponse.model_validate(response)

    def delete_datasource(self, datasource_id: str) -> str:
        """
        Delete Datasource
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("DELETE", path)
        return response


class AsyncDatasourcesResource:
    """Datasources resource operations (async)."""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def list_datasources(self) -> AsyncPaginatedIterator["DatasourceResponse"]:
        """
        List Datasources
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources"
        return AsyncPaginatedIterator(
            self._http,
            "GET",
            path,
            items_field="datasources",
            cursor_param="offset",
            next_field="next_cursor",
        )

    async def create_datasource(self, body: "CreateDatasourceRequest") -> "DatasourceResponse":
        """
        Create Datasource
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources"
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return DatasourceResponse.model_validate(response)

    async def get_datasource(self, datasource_id: str) -> "DatasourceResponse":
        """
        Get Datasource
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("GET", path)
        return DatasourceResponse.model_validate(response)

    async def update_datasource(self, datasource_id: str, body: "UpdateDatasourceRequest") -> "DatasourceResponse":
        """
        Update Datasource
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return DatasourceResponse.model_validate(response)

    async def delete_datasource(self, datasource_id: str) -> str:
        """
        Delete Datasource
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("DELETE", path)
        return response
