"""
Datasources resource operations.

Generated by Forge SDK Generator.
"""

from __future__ import annotations

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .data_elements import DataElementsResource, AsyncDataElementsResource
    from .downloads import DownloadsResource, AsyncDownloadsResource
    from .file_uploads import FileUploadsResource, AsyncFileUploadsResource
    from .ingest import IngestResource, AsyncIngestResource
    from .tables import TablesResource, AsyncTablesResource


class DatasourcesResource:
    """Manage data source connections"""

    data_elements: DataElementsResource
    downloads: DownloadsResource
    file_uploads: FileUploadsResource
    ingest: IngestResource
    tables: TablesResource

    def __init__(self, http: HttpClient):
        self._http = http

    def list(self) -> "DatasourceListResponse":
        """
        List Datasources
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources"
        response = self._http.request("GET", path)
        return DatasourceListResponse.model_validate(response)

    def create(self, body: "CreateDatasourceRequest") -> "DatasourceResponse":
        """
        Create Datasource
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources"
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return DatasourceResponse.model_validate(response)

    def get(self, datasource_id: str, include_tables: Optional[bool] = None) -> "DatasourceResponse":
        """
        Get Datasource
        
        Args:
            datasource_id: The datasource_id parameter
            include_tables: Include table and column details (structured datasources only)
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        params = {}
        if include_tables is not None:
            params["include_tables"] = include_tables
        response = self._http.request("GET", path, params=params)
        return DatasourceResponse.model_validate(response)

    def update(self, datasource_id: str, body: "UpdateDatasourceRequest") -> "DatasourceResponse":
        """
        Update Datasource
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return DatasourceResponse.model_validate(response)

    def delete(self, datasource_id: str) -> str:
        """
        Delete Datasource
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("DELETE", path)
        return response


class AsyncDatasourcesResource:
    """Manage data source connections (async)"""

    data_elements: AsyncDataElementsResource
    downloads: AsyncDownloadsResource
    file_uploads: AsyncFileUploadsResource
    ingest: AsyncIngestResource
    tables: AsyncTablesResource

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def list(self) -> "DatasourceListResponse":
        """
        List Datasources
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources"
        response = await self._http.request("GET", path)
        return DatasourceListResponse.model_validate(response)

    async def create(self, body: "CreateDatasourceRequest") -> "DatasourceResponse":
        """
        Create Datasource
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources"
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return DatasourceResponse.model_validate(response)

    async def get(self, datasource_id: str, include_tables: Optional[bool] = None) -> "DatasourceResponse":
        """
        Get Datasource
        
        Args:
            datasource_id: The datasource_id parameter
            include_tables: Include table and column details (structured datasources only)
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        params = {}
        if include_tables is not None:
            params["include_tables"] = include_tables
        response = await self._http.request("GET", path, params=params)
        return DatasourceResponse.model_validate(response)

    async def update(self, datasource_id: str, body: "UpdateDatasourceRequest") -> "DatasourceResponse":
        """
        Update Datasource
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return DatasourceResponse.model_validate(response)

    async def delete(self, datasource_id: str) -> str:
        """
        Delete Datasource
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("DELETE", path)
        return response
