"""
datasources.tag resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status


class DatasourcesTagResource:
    """datasources.tag resource operations."""

    def __init__(self, http: HttpClient):
        self._http = http

    def get_tag_config(self, datasource_id: str) -> "TagConfig":
        """
        Get Tag Config
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("GET", path)
        return TagConfig.model_validate(response)

    def add_tag_config(self, datasource_id: str, body: "AddTagConfigRequest") -> "AddTagConfigResponse":
        """
        Add Tag Config
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return AddTagConfigResponse.model_validate(response)

    def update_tag_config(self, datasource_id: str, body: "UpdateTagConfigRequest") -> "UpdateTagConfigResponse":
        """
        Update Tag Config
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return UpdateTagConfigResponse.model_validate(response)

    def delete_tag_config(self, datasource_id: str) -> str:
        """
        Delete Tag Config
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("DELETE", path)
        return response

    def get_tag_table_info(self, datasource_id: str, table_name: str) -> "TagTableInfo":
        """
        Get Tag Table Info
        
        Args:
            datasource_id: The datasource_id parameter
            table_name: The table_name parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info/{table_name}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{table_name}", str(table_name))
        response = self._http.request("GET", path)
        return TagTableInfo.model_validate(response)

    def add_tag_table_info(self, datasource_id: str, table_name: str, body: "AddTagTableRequest") -> "AddTagTableResponse":
        """
        Add Tag Table Info
        
        Args:
            datasource_id: The datasource_id parameter
            table_name: The table_name parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info/{table_name}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{table_name}", str(table_name))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return AddTagTableResponse.model_validate(response)

    def update_tag_table_info(self, datasource_id: str, table_name: str, body: "UpdateTagTableRequest") -> "UpdateTagTableResponse":
        """
        Update Tag Table Info
        
        Args:
            datasource_id: The datasource_id parameter
            table_name: The table_name parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info/{table_name}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{table_name}", str(table_name))
        response = self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return UpdateTagTableResponse.model_validate(response)

    def delete_tag_table_info(self, datasource_id: str, table_name: str) -> "DeleteTagTableResponse":
        """
        Delete Tag Table Info
        
        Args:
            datasource_id: The datasource_id parameter
            table_name: The table_name parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info/{table_name}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{table_name}", str(table_name))
        response = self._http.request("DELETE", path)
        return DeleteTagTableResponse.model_validate(response)

    def get_all_tag_table_info(self, datasource_id: str) -> List["TagTableInfo"]:
        """
        Get All Tag Table Info
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("GET", path)
        return [TagTableInfo.model_validate(item) for item in response]

    def get_tag_column_info(self, datasource_id: str, table_name: str, column_name: str) -> "TagColumnInfo":
        """
        Get Tag Column Info
        
        Args:
            datasource_id: The datasource_id parameter
            table_name: The table_name parameter
            column_name: The column_name parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info/{table_name}/column_info/{column_name}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{table_name}", str(table_name))
        path = path.replace("{column_name}", str(column_name))
        response = self._http.request("GET", path)
        return TagColumnInfo.model_validate(response)

    def add_tag_column_info(self, datasource_id: str, table_name: str, column_name: str, body: "AddTagColumnRequest") -> "AddTagColumnResponse":
        """
        Add Tag Column Info
        
        Args:
            datasource_id: The datasource_id parameter
            table_name: The table_name parameter
            column_name: The column_name parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info/{table_name}/column_info/{column_name}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{table_name}", str(table_name))
        path = path.replace("{column_name}", str(column_name))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return AddTagColumnResponse.model_validate(response)

    def update_tag_column_info(self, datasource_id: str, table_name: str, column_name: str, body: "UpdateTagColumnRequest") -> "UpdateTagColumnResponse":
        """
        Update Tag Column Info
        
        Args:
            datasource_id: The datasource_id parameter
            table_name: The table_name parameter
            column_name: The column_name parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info/{table_name}/column_info/{column_name}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{table_name}", str(table_name))
        path = path.replace("{column_name}", str(column_name))
        response = self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return UpdateTagColumnResponse.model_validate(response)

    def delete_tag_column_info(self, datasource_id: str, table_name: str, column_name: str) -> "DeleteTagTableResponse":
        """
        Delete Tag Column Info
        
        Args:
            datasource_id: The datasource_id parameter
            table_name: The table_name parameter
            column_name: The column_name parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info/{table_name}/column_info/{column_name}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{table_name}", str(table_name))
        path = path.replace("{column_name}", str(column_name))
        response = self._http.request("DELETE", path)
        return DeleteTagTableResponse.model_validate(response)

    def get_all_tag_column_info(self, datasource_id: str, table_name: str) -> List["TagColumnInfo"]:
        """
        Get All Tag Column Info
        
        Args:
            datasource_id: The datasource_id parameter
            table_name: The table_name parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info/{table_name}/column_info"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{table_name}", str(table_name))
        response = self._http.request("GET", path)
        return [TagColumnInfo.model_validate(item) for item in response]


class AsyncDatasourcesTagResource:
    """datasources.tag resource operations (async)."""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def get_tag_config(self, datasource_id: str) -> "TagConfig":
        """
        Get Tag Config
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("GET", path)
        return TagConfig.model_validate(response)

    async def add_tag_config(self, datasource_id: str, body: "AddTagConfigRequest") -> "AddTagConfigResponse":
        """
        Add Tag Config
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return AddTagConfigResponse.model_validate(response)

    async def update_tag_config(self, datasource_id: str, body: "UpdateTagConfigRequest") -> "UpdateTagConfigResponse":
        """
        Update Tag Config
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return UpdateTagConfigResponse.model_validate(response)

    async def delete_tag_config(self, datasource_id: str) -> str:
        """
        Delete Tag Config
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("DELETE", path)
        return response

    async def get_tag_table_info(self, datasource_id: str, table_name: str) -> "TagTableInfo":
        """
        Get Tag Table Info
        
        Args:
            datasource_id: The datasource_id parameter
            table_name: The table_name parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info/{table_name}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{table_name}", str(table_name))
        response = await self._http.request("GET", path)
        return TagTableInfo.model_validate(response)

    async def add_tag_table_info(self, datasource_id: str, table_name: str, body: "AddTagTableRequest") -> "AddTagTableResponse":
        """
        Add Tag Table Info
        
        Args:
            datasource_id: The datasource_id parameter
            table_name: The table_name parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info/{table_name}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{table_name}", str(table_name))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return AddTagTableResponse.model_validate(response)

    async def update_tag_table_info(self, datasource_id: str, table_name: str, body: "UpdateTagTableRequest") -> "UpdateTagTableResponse":
        """
        Update Tag Table Info
        
        Args:
            datasource_id: The datasource_id parameter
            table_name: The table_name parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info/{table_name}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{table_name}", str(table_name))
        response = await self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return UpdateTagTableResponse.model_validate(response)

    async def delete_tag_table_info(self, datasource_id: str, table_name: str) -> "DeleteTagTableResponse":
        """
        Delete Tag Table Info
        
        Args:
            datasource_id: The datasource_id parameter
            table_name: The table_name parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info/{table_name}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{table_name}", str(table_name))
        response = await self._http.request("DELETE", path)
        return DeleteTagTableResponse.model_validate(response)

    async def get_all_tag_table_info(self, datasource_id: str) -> List["TagTableInfo"]:
        """
        Get All Tag Table Info
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("GET", path)
        return [TagTableInfo.model_validate(item) for item in response]

    async def get_tag_column_info(self, datasource_id: str, table_name: str, column_name: str) -> "TagColumnInfo":
        """
        Get Tag Column Info
        
        Args:
            datasource_id: The datasource_id parameter
            table_name: The table_name parameter
            column_name: The column_name parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info/{table_name}/column_info/{column_name}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{table_name}", str(table_name))
        path = path.replace("{column_name}", str(column_name))
        response = await self._http.request("GET", path)
        return TagColumnInfo.model_validate(response)

    async def add_tag_column_info(self, datasource_id: str, table_name: str, column_name: str, body: "AddTagColumnRequest") -> "AddTagColumnResponse":
        """
        Add Tag Column Info
        
        Args:
            datasource_id: The datasource_id parameter
            table_name: The table_name parameter
            column_name: The column_name parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info/{table_name}/column_info/{column_name}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{table_name}", str(table_name))
        path = path.replace("{column_name}", str(column_name))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return AddTagColumnResponse.model_validate(response)

    async def update_tag_column_info(self, datasource_id: str, table_name: str, column_name: str, body: "UpdateTagColumnRequest") -> "UpdateTagColumnResponse":
        """
        Update Tag Column Info
        
        Args:
            datasource_id: The datasource_id parameter
            table_name: The table_name parameter
            column_name: The column_name parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info/{table_name}/column_info/{column_name}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{table_name}", str(table_name))
        path = path.replace("{column_name}", str(column_name))
        response = await self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return UpdateTagColumnResponse.model_validate(response)

    async def delete_tag_column_info(self, datasource_id: str, table_name: str, column_name: str) -> "DeleteTagTableResponse":
        """
        Delete Tag Column Info
        
        Args:
            datasource_id: The datasource_id parameter
            table_name: The table_name parameter
            column_name: The column_name parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info/{table_name}/column_info/{column_name}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{table_name}", str(table_name))
        path = path.replace("{column_name}", str(column_name))
        response = await self._http.request("DELETE", path)
        return DeleteTagTableResponse.model_validate(response)

    async def get_all_tag_column_info(self, datasource_id: str, table_name: str) -> List["TagColumnInfo"]:
        """
        Get All Tag Column Info
        
        Args:
            datasource_id: The datasource_id parameter
            table_name: The table_name parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/tag_table_info/{table_name}/column_info"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{table_name}", str(table_name))
        response = await self._http.request("GET", path)
        return [TagColumnInfo.model_validate(item) for item in response]
