"""
datasources.rag resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status


class DatasourcesRagResource:
    """datasources.rag resource operations."""

    def __init__(self, http: HttpClient):
        self._http = http

    def get_rag_config(self, datasource_id: str) -> "RagConfig":
        """
        Get Rag Config
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/rag_config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("GET", path)
        return RagConfig.model_validate(response)

    def add_rag_config(self, datasource_id: str, body: "AddRagConfigRequest") -> "AddRagConfigResponse":
        """
        Add Rag Config
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/rag_config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return AddRagConfigResponse.model_validate(response)

    def update_rag_config(self, datasource_id: str, body: "UpdateRagConfigRequest") -> "UpdateRagConfigResponse":
        """
        Update Rag Config
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/rag_config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return UpdateRagConfigResponse.model_validate(response)

    def delete_rag_config(self, datasource_id: str) -> str:
        """
        Delete Rag Config
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/rag_config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("DELETE", path)
        return response

    def get_chunking_strategy(self, datasource_id: str) -> "RagChunkingStrategy":
        """
        Get Chunking Strategy
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/chunking_strategy"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("GET", path)
        return RagChunkingStrategy.model_validate(response)

    def add_chunking_strategy(self, datasource_id: str, body: "AddChunkingStrategyRequest") -> "AddChunkingStrategyResponse":
        """
        Add Chunking Strategy
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/chunking_strategy"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return AddChunkingStrategyResponse.model_validate(response)

    def update_chunking_strategy(self, datasource_id: str, body: "UpdateChunkingStrategyRequest") -> "UpdateChunkingStrategyResponse":
        """
        Update Chunking Strategy
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/chunking_strategy"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return UpdateChunkingStrategyResponse.model_validate(response)

    def delete_chunking_strategy(self, datasource_id: str) -> "DeleteChunkingStrategyResponse":
        """
        Delete Chunking Strategy
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/chunking_strategy"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("DELETE", path)
        return DeleteChunkingStrategyResponse.model_validate(response)

    def reprocess_datasource_metadata(self, datasource_id: str, body: "ReprocessDatasourceRequest") -> "ReprocessDatasourceResponse":
        """
        Reprocess Datasource Metadata
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/reprocess_metadata"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return ReprocessDatasourceResponse.model_validate(response)

    def get_reprocess_metadata_status(self, datasource_id: str) -> "GetReprocessStatusResponse":
        """
        Get Reprocess Metadata Status
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/reprocess_metadata/status"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("GET", path)
        return GetReprocessStatusResponse.model_validate(response)

    def patch_rag_config_metadata(self, datasource_id: str, body: "PatchRagConfigMetadataRequest") -> "PatchRagConfigMetadataResponse":
        """
        Patch Rag Config Metadata
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/rag_config/metadata"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("PATCH", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return PatchRagConfigMetadataResponse.model_validate(response)


class AsyncDatasourcesRagResource:
    """datasources.rag resource operations (async)."""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def get_rag_config(self, datasource_id: str) -> "RagConfig":
        """
        Get Rag Config
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/rag_config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("GET", path)
        return RagConfig.model_validate(response)

    async def add_rag_config(self, datasource_id: str, body: "AddRagConfigRequest") -> "AddRagConfigResponse":
        """
        Add Rag Config
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/rag_config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return AddRagConfigResponse.model_validate(response)

    async def update_rag_config(self, datasource_id: str, body: "UpdateRagConfigRequest") -> "UpdateRagConfigResponse":
        """
        Update Rag Config
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/rag_config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return UpdateRagConfigResponse.model_validate(response)

    async def delete_rag_config(self, datasource_id: str) -> str:
        """
        Delete Rag Config
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/rag_config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("DELETE", path)
        return response

    async def get_chunking_strategy(self, datasource_id: str) -> "RagChunkingStrategy":
        """
        Get Chunking Strategy
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/chunking_strategy"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("GET", path)
        return RagChunkingStrategy.model_validate(response)

    async def add_chunking_strategy(self, datasource_id: str, body: "AddChunkingStrategyRequest") -> "AddChunkingStrategyResponse":
        """
        Add Chunking Strategy
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/chunking_strategy"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return AddChunkingStrategyResponse.model_validate(response)

    async def update_chunking_strategy(self, datasource_id: str, body: "UpdateChunkingStrategyRequest") -> "UpdateChunkingStrategyResponse":
        """
        Update Chunking Strategy
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/chunking_strategy"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return UpdateChunkingStrategyResponse.model_validate(response)

    async def delete_chunking_strategy(self, datasource_id: str) -> "DeleteChunkingStrategyResponse":
        """
        Delete Chunking Strategy
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/chunking_strategy"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("DELETE", path)
        return DeleteChunkingStrategyResponse.model_validate(response)

    async def reprocess_datasource_metadata(self, datasource_id: str, body: "ReprocessDatasourceRequest") -> "ReprocessDatasourceResponse":
        """
        Reprocess Datasource Metadata
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/reprocess_metadata"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return ReprocessDatasourceResponse.model_validate(response)

    async def get_reprocess_metadata_status(self, datasource_id: str) -> "GetReprocessStatusResponse":
        """
        Get Reprocess Metadata Status
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/reprocess_metadata/status"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("GET", path)
        return GetReprocessStatusResponse.model_validate(response)

    async def patch_rag_config_metadata(self, datasource_id: str, body: "PatchRagConfigMetadataRequest") -> "PatchRagConfigMetadataResponse":
        """
        Patch Rag Config Metadata
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/rag_config/metadata"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("PATCH", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return PatchRagConfigMetadataResponse.model_validate(response)
