"""
dataelements resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status


class DataelementsResource:
    """dataelements resource operations."""

    def __init__(self, http: HttpClient):
        self._http = http

    def get_data_elements(self, datasource_id: str, offset: Optional[int] = None, limit: Optional[int] = None, sort_by: Optional[Union[str, None]] = None, sort_order: Optional[Union[str, None]] = None) -> List["DataElement"]:
        """
        Get Data Elements
        
        Args:
            datasource_id: The datasource_id parameter
            offset: Number of items to skip
            limit: Maximum number of items to return
            sort_by: Field to sort by
            sort_order: Sort order (asc or desc)
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/data_element"
        path = path.replace("{datasource_id}", str(datasource_id))
        params = {}
        if offset is not None:
            params["offset"] = offset
        if limit is not None:
            params["limit"] = limit
        if sort_by is not None:
            params["sort_by"] = sort_by
        if sort_order is not None:
            params["sort_order"] = sort_order
        response = self._http.request("GET", path, params=params)
        return [DataElement.model_validate(item) for item in response]

    def add_data_element(self, datasource_id: str, body: "AddDataElementRequest") -> "AddDataElementResponse":
        """
        Add Data Element
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/data_element"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return AddDataElementResponse.model_validate(response)

    def get_data_element(self, datasource_id: str, data_element_id: str) -> "DataElement":
        """
        Get Data Element
        
        Args:
            datasource_id: The datasource_id parameter
            data_element_id: The data_element_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/data_element/{data_element_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{data_element_id}", str(data_element_id))
        response = self._http.request("GET", path)
        return DataElement.model_validate(response)

    def update_data_element(self, datasource_id: str, data_element_id: str, body: "UpdateDataElementRequest") -> "UpdateDataElementResponse":
        """
        Update Data Element
        
        Args:
            datasource_id: The datasource_id parameter
            data_element_id: The data_element_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/data_element/{data_element_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{data_element_id}", str(data_element_id))
        response = self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return UpdateDataElementResponse.model_validate(response)

    def delete_data_element(self, datasource_id: str, data_element_id: str) -> "DeleteDataElementResponse":
        """
        Delete Data Element
        
        Args:
            datasource_id: The datasource_id parameter
            data_element_id: The data_element_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/data_element/{data_element_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{data_element_id}", str(data_element_id))
        response = self._http.request("DELETE", path)
        return DeleteDataElementResponse.model_validate(response)

    def get_data_elements_by_filters(self, datasource_id: str, body: Optional["DataElementFilterRequest"] = None, regex_filter: Optional[str] = None, media_type_filters: Optional[List[str]] = None, offset: Optional[int] = None, limit: Optional[int] = None, sort_by: Optional[Union[str, None]] = None, sort_order: Optional[Union[str, None]] = None) -> List["DataElement"]:
        """
        Get Data Elements By Filters
        
        Args:
            datasource_id: The datasource_id parameter
            regex_filter: The regex_filter parameter
            media_type_filters: The media_type_filters parameter
            offset: Number of items to skip
            limit: Maximum number of items to return
            sort_by: Field to sort by
            sort_order: Sort order (asc or desc)
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/data_elements_by_filters"
        path = path.replace("{datasource_id}", str(datasource_id))
        params = {}
        if regex_filter is not None:
            params["regex_filter"] = regex_filter
        if media_type_filters is not None:
            params["media_type_filters"] = media_type_filters
        if offset is not None:
            params["offset"] = offset
        if limit is not None:
            params["limit"] = limit
        if sort_by is not None:
            params["sort_by"] = sort_by
        if sort_order is not None:
            params["sort_order"] = sort_order
        response = self._http.request("POST", path, params=params, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return [DataElement.model_validate(item) for item in response]


class AsyncDataelementsResource:
    """dataelements resource operations (async)."""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def get_data_elements(self, datasource_id: str, offset: Optional[int] = None, limit: Optional[int] = None, sort_by: Optional[Union[str, None]] = None, sort_order: Optional[Union[str, None]] = None) -> List["DataElement"]:
        """
        Get Data Elements
        
        Args:
            datasource_id: The datasource_id parameter
            offset: Number of items to skip
            limit: Maximum number of items to return
            sort_by: Field to sort by
            sort_order: Sort order (asc or desc)
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/data_element"
        path = path.replace("{datasource_id}", str(datasource_id))
        params = {}
        if offset is not None:
            params["offset"] = offset
        if limit is not None:
            params["limit"] = limit
        if sort_by is not None:
            params["sort_by"] = sort_by
        if sort_order is not None:
            params["sort_order"] = sort_order
        response = await self._http.request("GET", path, params=params)
        return [DataElement.model_validate(item) for item in response]

    async def add_data_element(self, datasource_id: str, body: "AddDataElementRequest") -> "AddDataElementResponse":
        """
        Add Data Element
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/data_element"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return AddDataElementResponse.model_validate(response)

    async def get_data_element(self, datasource_id: str, data_element_id: str) -> "DataElement":
        """
        Get Data Element
        
        Args:
            datasource_id: The datasource_id parameter
            data_element_id: The data_element_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/data_element/{data_element_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{data_element_id}", str(data_element_id))
        response = await self._http.request("GET", path)
        return DataElement.model_validate(response)

    async def update_data_element(self, datasource_id: str, data_element_id: str, body: "UpdateDataElementRequest") -> "UpdateDataElementResponse":
        """
        Update Data Element
        
        Args:
            datasource_id: The datasource_id parameter
            data_element_id: The data_element_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/data_element/{data_element_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{data_element_id}", str(data_element_id))
        response = await self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return UpdateDataElementResponse.model_validate(response)

    async def delete_data_element(self, datasource_id: str, data_element_id: str) -> "DeleteDataElementResponse":
        """
        Delete Data Element
        
        Args:
            datasource_id: The datasource_id parameter
            data_element_id: The data_element_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/data_element/{data_element_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{data_element_id}", str(data_element_id))
        response = await self._http.request("DELETE", path)
        return DeleteDataElementResponse.model_validate(response)

    async def get_data_elements_by_filters(self, datasource_id: str, body: Optional["DataElementFilterRequest"] = None, regex_filter: Optional[str] = None, media_type_filters: Optional[List[str]] = None, offset: Optional[int] = None, limit: Optional[int] = None, sort_by: Optional[Union[str, None]] = None, sort_order: Optional[Union[str, None]] = None) -> List["DataElement"]:
        """
        Get Data Elements By Filters
        
        Args:
            datasource_id: The datasource_id parameter
            regex_filter: The regex_filter parameter
            media_type_filters: The media_type_filters parameter
            offset: Number of items to skip
            limit: Maximum number of items to return
            sort_by: Field to sort by
            sort_order: Sort order (asc or desc)
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasource/{datasource_id}/data_elements_by_filters"
        path = path.replace("{datasource_id}", str(datasource_id))
        params = {}
        if regex_filter is not None:
            params["regex_filter"] = regex_filter
        if media_type_filters is not None:
            params["media_type_filters"] = media_type_filters
        if offset is not None:
            params["offset"] = offset
        if limit is not None:
            params["limit"] = limit
        if sort_by is not None:
            params["sort_by"] = sort_by
        if sort_order is not None:
            params["sort_order"] = sort_order
        response = await self._http.request("POST", path, params=params, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return [DataElement.model_validate(item) for item in response]
