"""
Data Elements resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status
from .._pagination import PaginatedIterator, AsyncPaginatedIterator


class DataElementsResource:
    """Data Elements resource operations."""

    def __init__(self, http: HttpClient):
        self._http = http

    def list_data_elements(self, datasource_id: str) -> PaginatedIterator[str]:
        """
        List Data Elements
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/data-elements"
        path = path.replace("{datasource_id}", str(datasource_id))
        return PaginatedIterator(
            self._http,
            "GET",
            path,
            items_field="items",
            cursor_param="offset",
            next_field="next_cursor",
        )

    def create_data_element(self, datasource_id: str, body: "CreateDataElementRequest") -> "DataElementResponse":
        """
        Create Data Element
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/data-elements"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return DataElementResponse.model_validate(response)

    def get_data_element(self, datasource_id: str, data_element_id: str) -> "DataElementResponse":
        """
        Get Data Element
        
        Args:
            datasource_id: The datasource_id parameter
            data_element_id: The data_element_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/data-elements/{data_element_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{data_element_id}", str(data_element_id))
        response = self._http.request("GET", path)
        return DataElementResponse.model_validate(response)

    def update_data_element(self, datasource_id: str, data_element_id: str, body: "UpdateDataElementRequest") -> "DataElementResponse":
        """
        Update Data Element
        
        Args:
            datasource_id: The datasource_id parameter
            data_element_id: The data_element_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/data-elements/{data_element_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{data_element_id}", str(data_element_id))
        response = self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return DataElementResponse.model_validate(response)

    def delete_data_element(self, datasource_id: str, data_element_id: str) -> str:
        """
        Delete Data Element
        
        Args:
            datasource_id: The datasource_id parameter
            data_element_id: The data_element_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/data-elements/{data_element_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{data_element_id}", str(data_element_id))
        response = self._http.request("DELETE", path)
        return response

    def search_data_elements(self, datasource_id: str, body: "DataElementSearchRequest") -> List["DataElementResponse"]:
        """
        Search Data Elements
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/data-elements/search"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return [DataElementResponse.model_validate(item) for item in response]


class AsyncDataElementsResource:
    """Data Elements resource operations (async)."""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def list_data_elements(self, datasource_id: str) -> AsyncPaginatedIterator[str]:
        """
        List Data Elements
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/data-elements"
        path = path.replace("{datasource_id}", str(datasource_id))
        return AsyncPaginatedIterator(
            self._http,
            "GET",
            path,
            items_field="items",
            cursor_param="offset",
            next_field="next_cursor",
        )

    async def create_data_element(self, datasource_id: str, body: "CreateDataElementRequest") -> "DataElementResponse":
        """
        Create Data Element
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/data-elements"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return DataElementResponse.model_validate(response)

    async def get_data_element(self, datasource_id: str, data_element_id: str) -> "DataElementResponse":
        """
        Get Data Element
        
        Args:
            datasource_id: The datasource_id parameter
            data_element_id: The data_element_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/data-elements/{data_element_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{data_element_id}", str(data_element_id))
        response = await self._http.request("GET", path)
        return DataElementResponse.model_validate(response)

    async def update_data_element(self, datasource_id: str, data_element_id: str, body: "UpdateDataElementRequest") -> "DataElementResponse":
        """
        Update Data Element
        
        Args:
            datasource_id: The datasource_id parameter
            data_element_id: The data_element_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/data-elements/{data_element_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{data_element_id}", str(data_element_id))
        response = await self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return DataElementResponse.model_validate(response)

    async def delete_data_element(self, datasource_id: str, data_element_id: str) -> str:
        """
        Delete Data Element
        
        Args:
            datasource_id: The datasource_id parameter
            data_element_id: The data_element_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/data-elements/{data_element_id}"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{data_element_id}", str(data_element_id))
        response = await self._http.request("DELETE", path)
        return response

    async def search_data_elements(self, datasource_id: str, body: "DataElementSearchRequest") -> List["DataElementResponse"]:
        """
        Search Data Elements
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/data-elements/search"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return [DataElementResponse.model_validate(item) for item in response]
