"""
Documents resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status
from .._pagination import PaginatedIterator, AsyncPaginatedIterator
from .._streaming import SSEIterator, AsyncSSEIterator
from typing import BinaryIO
from pydantic import BaseModel
from typing import Type


def _is_pydantic_model(obj) -> bool:
    """Check if obj is a Pydantic BaseModel subclass (not an instance)."""
    try:
        return issubclass(obj, BaseModel)
    except TypeError:
        return False


class DocumentsResource:
    """Parse and transform documents into structured data"""

    def __init__(self, http: HttpClient):
        self._http = http

    def list_deep_transforms(self, offset: Optional[int] = None, limit: Optional[int] = None) -> PaginatedIterator["DeepTransformJob"]:
        """
        List deep-transform jobs
        
        List the calling customer's deep-transform jobs, newest first. Scoped to the customer (and project, when a project header is set). Paginated via `offset`/`limit`.
        
        Args:
            offset: Number of jobs to skip
            limit: Maximum number of jobs to return
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/deep-transform"
        params: Dict[str, Any] = {}
        if offset is not None:
            params["offset"] = offset
        if limit is not None:
            params["limit"] = limit
        return PaginatedIterator(
            self._http,
            "GET",
            path,
            items_field="jobs",
            cursor_param="offset",
            next_field="next_cursor",
            params=params,
            model_class=DeepTransformJob,
        )

    def submit_deep_transform(self, file: str, schema: Union[str, Dict[str, Any], Type[BaseModel]], root_name: Optional[str] = None, guidance: Optional[str] = None, max_pages: Optional[int] = None) -> "SubmitDeepTransformResponse":
        """
        Submit a deep-transform extraction from a file upload (async)
        
        Upload a document and submit an extraction against a JSON schema, returning immediately with a job id. To reuse an already-parsed document instead of uploading, use POST /documents/deep-transform/from-document. Poll status via GET /documents/deep-transform/{job_id} and download artifacts once it succeeds. Submission is idempotent on the (document, schema) pair.
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/deep-transform"
        if _is_pydantic_model(schema):
            _schema = schema.model_json_schema()
        else:
            _schema = schema
        import json as _json
        _file = open(file, "rb")
        _file_name = file.rsplit("/", 1)[-1] if "/" in file else file
        form_fields = {}
        if isinstance(_schema, (dict, list)):
            form_fields["schema"] = _json.dumps(_schema)
        elif _schema is not None:
            form_fields["schema"] = str(_schema)
        if root_name is not None:
            form_fields["root_name"] = str(root_name)
        if guidance is not None:
            form_fields["guidance"] = str(guidance)
        if max_pages is not None:
            form_fields["max_pages"] = str(max_pages)
        try:
            response = self._http.upload("POST", path, file=_file, file_name=_file_name, field_name="file", form_fields=form_fields)
        finally:
            _file.close()
        return SubmitDeepTransformResponse.model_validate(response)

    def submit_deep_transform_from(self, body: "SubmitDeepTransformFromDocument") -> "SubmitDeepTransformResponse":
        """
        Submit a deep-transform extraction reusing a parsed document (async)
        
        Submit an extraction that reuses an already-parsed document (by `document_job_id` from POST /documents) instead of re-parsing an upload. Returns immediately with a job id. Poll status via GET /documents/deep-transform/{job_id} and download artifacts once it succeeds. Submission is idempotent on the (document, schema) pair.
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/deep-transform/from-document"
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return SubmitDeepTransformResponse.model_validate(response)

    def get_deep_transform_status(self, job_id: str) -> "DeepTransformJob":
        """
        Get deep-transform job status
        
        Check status and, once succeeded, the list of downloadable artifacts.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/deep-transform/{job_id}"
        path = path.replace("{job_id}", str(job_id))
        response = self._http.request("GET", path)
        return DeepTransformJob.model_validate(response)

    def download_deep_transform_artifact(self, job_id: str, name: str) -> str:
        """
        Download a deep-transform artifact
        
        Download a named artifact (e.g. output.json) produced by a succeeded job. Ownership is verified against the customer header before any bytes are returned.
        
        Args:
            job_id: The job_id parameter
            name: The name parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/deep-transform/{job_id}/artifact/{name}"
        path = path.replace("{job_id}", str(job_id))
        path = path.replace("{name}", str(name))
        response = self._http.request("GET", path)
        return response

    def parse(self, file: BinaryIO, file_name: str) -> "ParseDocumentResponse":
        """
        Parse a document (async)
        
        Upload a document for asynchronous parsing. Returns a job ID to track progress.
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents"
        response = self._http.upload("POST", path, file=file, file_name=file_name, field_name="file")
        return ParseDocumentResponse.model_validate(response)

    def process(self, file: BinaryIO, file_name: str, format: Optional[str] = None) -> "ProcessDocumentResponse":
        """
        Parse a document (sync)
        
        Upload a document and block until parsing is complete. Returns the full parsed result.
        
        Args:
            format: Result format: markdown, annotated, docling, json
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/process"
        params: Dict[str, Any] = {}
        if format is not None:
            params["format"] = format
        response = self._http.upload("POST", path, file=file, file_name=file_name, field_name="file", params=params)
        return ProcessDocumentResponse.model_validate(response)

    def get_status(self, job_id: str) -> "DocumentStatus":
        """
        Get document parsing status
        
        Check the status of a document parsing job, including progress statistics.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/{job_id}"
        path = path.replace("{job_id}", str(job_id))
        response = self._http.request("GET", path)
        return DocumentStatus.model_validate(response)

    def get_result(self, job_id: str, format: Optional[str] = None) -> str:
        """
        Get parsed document result
        
        Download the parsed result of a completed document parsing job.
        
        Args:
            job_id: The job_id parameter
            format: Result format: markdown, annotated, docling, json
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/{job_id}/result"
        path = path.replace("{job_id}", str(job_id))
        params: Dict[str, Any] = {}
        if format is not None:
            params["format"] = format
        response = self._http.request("GET", path, params=params)
        return response

    def get_structured_result(self, job_id: str) -> "ParseStructuredDocument":
        """
        Get structured parse result
        
        Download the fully structured parse result (the json format): pages, typed elements, tables, chart data, chart OCR text, and bounding boxes. The response schema (StructuredDocument) is defined by the parsing engine and hoisted into this spec by the OpenAPI generator.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/{job_id}/structured"
        path = path.replace("{job_id}", str(job_id))
        response = self._http.request("GET", path)
        return ParseStructuredDocument.model_validate(response)

    def list_children(self, job_id: str) -> List["DocumentChild"]:
        """
        List child documents
        
        For container files (ZIP, TAR, EML), list the child documents extracted from the container.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/{job_id}/children"
        path = path.replace("{job_id}", str(job_id))
        response = self._http.request("GET", path)
        return [DocumentChild.model_validate(item) for item in response]

    def stream_trace(self, job_id: str) -> Iterator[Dict[str, Any]]:
        """
        Stream document parsing trace
        
        Subscribe to real-time parsing progress via Server-Sent Events.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/{job_id}/trace"
        path = path.replace("{job_id}", str(job_id))
        return self._http.stream("GET", path)

    def transform(self, file: str, schema: Union[str, Dict[str, Any], Type[BaseModel]], model: Optional[str] = None, prompt: Optional[str] = None, prompt_id: Optional[str] = None, timeout_seconds: int = 600) -> "TransformDocumentResponse":
        """
        Transform a document using AI extraction (sync)
        
        Upload a document for AI-powered structured extraction and block until complete. The file is uploaded to cloud storage and processed by a system agent.
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/transform"
        if _is_pydantic_model(schema):
            _schema = schema.model_json_schema()
        else:
            _schema = schema
        import json as _json
        _file = open(file, "rb")
        _file_name = file.rsplit("/", 1)[-1] if "/" in file else file
        form_fields = {}
        if isinstance(_schema, (dict, list)):
            form_fields["artifact_schema"] = _json.dumps(_schema)
        elif _schema is not None:
            form_fields["artifact_schema"] = str(_schema)
        if model is not None:
            form_fields["model"] = str(model)
        if prompt is not None:
            form_fields["prompt"] = str(prompt)
        if prompt_id is not None:
            form_fields["prompt_id"] = str(prompt_id)
        if timeout_seconds is not None:
            form_fields["timeout_seconds"] = str(timeout_seconds)
        try:
            response = self._http.upload("POST", path, file=_file, file_name=_file_name, field_name="file", form_fields=form_fields, timeout=float(timeout_seconds or self._http._timeout))
        finally:
            _file.close()
        return TransformDocumentResponse.model_validate(response)

    def submit_transform(self, file: str, schema: Union[str, Dict[str, Any], Type[BaseModel]], model: Optional[str] = None, prompt: Optional[str] = None, prompt_id: Optional[str] = None, timeout_seconds: int = 600) -> "SubmitDocumentTransformResponse":
        """
        Submit a document transform (async)
        
        Upload a document for AI-powered extraction and return immediately. Poll for completion via client.sessions.get(execution_id).
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/transform/submit"
        if _is_pydantic_model(schema):
            _schema = schema.model_json_schema()
        else:
            _schema = schema
        import json as _json
        _file = open(file, "rb")
        _file_name = file.rsplit("/", 1)[-1] if "/" in file else file
        form_fields = {}
        if isinstance(_schema, (dict, list)):
            form_fields["artifact_schema"] = _json.dumps(_schema)
        elif _schema is not None:
            form_fields["artifact_schema"] = str(_schema)
        if model is not None:
            form_fields["model"] = str(model)
        if prompt is not None:
            form_fields["prompt"] = str(prompt)
        if prompt_id is not None:
            form_fields["prompt_id"] = str(prompt_id)
        if timeout_seconds is not None:
            form_fields["timeout_seconds"] = str(timeout_seconds)
        try:
            response = self._http.upload("POST", path, file=_file, file_name=_file_name, field_name="file", form_fields=form_fields, timeout=float(timeout_seconds or self._http._timeout))
        finally:
            _file.close()
        return SubmitDocumentTransformResponse.model_validate(response)

    def move(self, body: "MoveDocumentsRequest") -> "MoveDocumentsResponse":
        """
        Move documents into a datasource (async)
        
        Move documents (identified by their parse job IDs, e.g. the job_id returned by parseDocument) into an existing datasource or a newly created one. Returns a workflow_id to poll for completion.
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/move"
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return MoveDocumentsResponse.model_validate(response)


class AsyncDocumentsResource:
    """Parse and transform documents into structured data (async)"""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def list_deep_transforms(self, offset: Optional[int] = None, limit: Optional[int] = None) -> AsyncPaginatedIterator["DeepTransformJob"]:
        """
        List deep-transform jobs
        
        List the calling customer's deep-transform jobs, newest first. Scoped to the customer (and project, when a project header is set). Paginated via `offset`/`limit`.
        
        Args:
            offset: Number of jobs to skip
            limit: Maximum number of jobs to return
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/deep-transform"
        params: Dict[str, Any] = {}
        if offset is not None:
            params["offset"] = offset
        if limit is not None:
            params["limit"] = limit
        return AsyncPaginatedIterator(
            self._http,
            "GET",
            path,
            items_field="jobs",
            cursor_param="offset",
            next_field="next_cursor",
            params=params,
            model_class=DeepTransformJob,
        )

    async def submit_deep_transform(self, file: str, schema: Union[str, Dict[str, Any], Type[BaseModel]], root_name: Optional[str] = None, guidance: Optional[str] = None, max_pages: Optional[int] = None) -> "SubmitDeepTransformResponse":
        """
        Submit a deep-transform extraction from a file upload (async)
        
        Upload a document and submit an extraction against a JSON schema, returning immediately with a job id. To reuse an already-parsed document instead of uploading, use POST /documents/deep-transform/from-document. Poll status via GET /documents/deep-transform/{job_id} and download artifacts once it succeeds. Submission is idempotent on the (document, schema) pair.
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/deep-transform"
        if _is_pydantic_model(schema):
            _schema = schema.model_json_schema()
        else:
            _schema = schema
        import json as _json
        _file = open(file, "rb")
        _file_name = file.rsplit("/", 1)[-1] if "/" in file else file
        form_fields = {}
        if isinstance(_schema, (dict, list)):
            form_fields["schema"] = _json.dumps(_schema)
        elif _schema is not None:
            form_fields["schema"] = str(_schema)
        if root_name is not None:
            form_fields["root_name"] = str(root_name)
        if guidance is not None:
            form_fields["guidance"] = str(guidance)
        if max_pages is not None:
            form_fields["max_pages"] = str(max_pages)
        try:
            response = await self._http.upload("POST", path, file=_file, file_name=_file_name, field_name="file", form_fields=form_fields)
        finally:
            _file.close()
        return SubmitDeepTransformResponse.model_validate(response)

    async def submit_deep_transform_from(self, body: "SubmitDeepTransformFromDocument") -> "SubmitDeepTransformResponse":
        """
        Submit a deep-transform extraction reusing a parsed document (async)
        
        Submit an extraction that reuses an already-parsed document (by `document_job_id` from POST /documents) instead of re-parsing an upload. Returns immediately with a job id. Poll status via GET /documents/deep-transform/{job_id} and download artifacts once it succeeds. Submission is idempotent on the (document, schema) pair.
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/deep-transform/from-document"
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return SubmitDeepTransformResponse.model_validate(response)

    async def get_deep_transform_status(self, job_id: str) -> "DeepTransformJob":
        """
        Get deep-transform job status
        
        Check status and, once succeeded, the list of downloadable artifacts.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/deep-transform/{job_id}"
        path = path.replace("{job_id}", str(job_id))
        response = await self._http.request("GET", path)
        return DeepTransformJob.model_validate(response)

    async def download_deep_transform_artifact(self, job_id: str, name: str) -> str:
        """
        Download a deep-transform artifact
        
        Download a named artifact (e.g. output.json) produced by a succeeded job. Ownership is verified against the customer header before any bytes are returned.
        
        Args:
            job_id: The job_id parameter
            name: The name parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/deep-transform/{job_id}/artifact/{name}"
        path = path.replace("{job_id}", str(job_id))
        path = path.replace("{name}", str(name))
        response = await self._http.request("GET", path)
        return response

    async def parse(self, file: BinaryIO, file_name: str) -> "ParseDocumentResponse":
        """
        Parse a document (async)
        
        Upload a document for asynchronous parsing. Returns a job ID to track progress.
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents"
        response = await self._http.upload("POST", path, file=file, file_name=file_name, field_name="file")
        return ParseDocumentResponse.model_validate(response)

    async def process(self, file: BinaryIO, file_name: str, format: Optional[str] = None) -> "ProcessDocumentResponse":
        """
        Parse a document (sync)
        
        Upload a document and block until parsing is complete. Returns the full parsed result.
        
        Args:
            format: Result format: markdown, annotated, docling, json
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/process"
        params: Dict[str, Any] = {}
        if format is not None:
            params["format"] = format
        response = await self._http.upload("POST", path, file=file, file_name=file_name, field_name="file", params=params)
        return ProcessDocumentResponse.model_validate(response)

    async def get_status(self, job_id: str) -> "DocumentStatus":
        """
        Get document parsing status
        
        Check the status of a document parsing job, including progress statistics.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/{job_id}"
        path = path.replace("{job_id}", str(job_id))
        response = await self._http.request("GET", path)
        return DocumentStatus.model_validate(response)

    async def get_result(self, job_id: str, format: Optional[str] = None) -> str:
        """
        Get parsed document result
        
        Download the parsed result of a completed document parsing job.
        
        Args:
            job_id: The job_id parameter
            format: Result format: markdown, annotated, docling, json
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/{job_id}/result"
        path = path.replace("{job_id}", str(job_id))
        params: Dict[str, Any] = {}
        if format is not None:
            params["format"] = format
        response = await self._http.request("GET", path, params=params)
        return response

    async def get_structured_result(self, job_id: str) -> "ParseStructuredDocument":
        """
        Get structured parse result
        
        Download the fully structured parse result (the json format): pages, typed elements, tables, chart data, chart OCR text, and bounding boxes. The response schema (StructuredDocument) is defined by the parsing engine and hoisted into this spec by the OpenAPI generator.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/{job_id}/structured"
        path = path.replace("{job_id}", str(job_id))
        response = await self._http.request("GET", path)
        return ParseStructuredDocument.model_validate(response)

    async def list_children(self, job_id: str) -> List["DocumentChild"]:
        """
        List child documents
        
        For container files (ZIP, TAR, EML), list the child documents extracted from the container.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/{job_id}/children"
        path = path.replace("{job_id}", str(job_id))
        response = await self._http.request("GET", path)
        return [DocumentChild.model_validate(item) for item in response]

    async def stream_trace(self, job_id: str) -> AsyncIterator[Dict[str, Any]]:
        """
        Stream document parsing trace
        
        Subscribe to real-time parsing progress via Server-Sent Events.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/{job_id}/trace"
        path = path.replace("{job_id}", str(job_id))
        return await self._http.stream("GET", path)

    async def transform(self, file: str, schema: Union[str, Dict[str, Any], Type[BaseModel]], model: Optional[str] = None, prompt: Optional[str] = None, prompt_id: Optional[str] = None, timeout_seconds: int = 600) -> "TransformDocumentResponse":
        """
        Transform a document using AI extraction (sync)
        
        Upload a document for AI-powered structured extraction and block until complete. The file is uploaded to cloud storage and processed by a system agent.
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/transform"
        if _is_pydantic_model(schema):
            _schema = schema.model_json_schema()
        else:
            _schema = schema
        import json as _json
        _file = open(file, "rb")
        _file_name = file.rsplit("/", 1)[-1] if "/" in file else file
        form_fields = {}
        if isinstance(_schema, (dict, list)):
            form_fields["artifact_schema"] = _json.dumps(_schema)
        elif _schema is not None:
            form_fields["artifact_schema"] = str(_schema)
        if model is not None:
            form_fields["model"] = str(model)
        if prompt is not None:
            form_fields["prompt"] = str(prompt)
        if prompt_id is not None:
            form_fields["prompt_id"] = str(prompt_id)
        if timeout_seconds is not None:
            form_fields["timeout_seconds"] = str(timeout_seconds)
        try:
            response = await self._http.upload("POST", path, file=_file, file_name=_file_name, field_name="file", form_fields=form_fields, timeout=float(timeout_seconds or self._http._timeout))
        finally:
            _file.close()
        return TransformDocumentResponse.model_validate(response)

    async def submit_transform(self, file: str, schema: Union[str, Dict[str, Any], Type[BaseModel]], model: Optional[str] = None, prompt: Optional[str] = None, prompt_id: Optional[str] = None, timeout_seconds: int = 600) -> "SubmitDocumentTransformResponse":
        """
        Submit a document transform (async)
        
        Upload a document for AI-powered extraction and return immediately. Poll for completion via client.sessions.get(execution_id).
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/transform/submit"
        if _is_pydantic_model(schema):
            _schema = schema.model_json_schema()
        else:
            _schema = schema
        import json as _json
        _file = open(file, "rb")
        _file_name = file.rsplit("/", 1)[-1] if "/" in file else file
        form_fields = {}
        if isinstance(_schema, (dict, list)):
            form_fields["artifact_schema"] = _json.dumps(_schema)
        elif _schema is not None:
            form_fields["artifact_schema"] = str(_schema)
        if model is not None:
            form_fields["model"] = str(model)
        if prompt is not None:
            form_fields["prompt"] = str(prompt)
        if prompt_id is not None:
            form_fields["prompt_id"] = str(prompt_id)
        if timeout_seconds is not None:
            form_fields["timeout_seconds"] = str(timeout_seconds)
        try:
            response = await self._http.upload("POST", path, file=_file, file_name=_file_name, field_name="file", form_fields=form_fields, timeout=float(timeout_seconds or self._http._timeout))
        finally:
            _file.close()
        return SubmitDocumentTransformResponse.model_validate(response)

    async def move(self, body: "MoveDocumentsRequest") -> "MoveDocumentsResponse":
        """
        Move documents into a datasource (async)
        
        Move documents (identified by their parse job IDs, e.g. the job_id returned by parseDocument) into an existing datasource or a newly created one. Returns a workflow_id to poll for completion.
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/move"
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return MoveDocumentsResponse.model_validate(response)
