"""
Documents resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status
from .._streaming import SSEIterator, AsyncSSEIterator
from typing import BinaryIO


class DocumentsResource:
    """Parse and transform documents into structured data"""

    def __init__(self, http: HttpClient):
        self._http = http

    def parse(self, file: BinaryIO, file_name: str) -> "ParseDocumentResponse":
        """
        Parse a document (async)
        
        Upload a document for asynchronous parsing. Returns a job ID to track progress.
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents"
        response = self._http.upload("POST", path, file=file, file_name=file_name, field_name="file")
        return ParseDocumentResponse.model_validate(response)

    def process(self, file: BinaryIO, file_name: str) -> "ProcessDocumentResponse":
        """
        Parse a document (sync)
        
        Upload a document and block until parsing is complete. Returns the full parsed result.
        
        Args:
            format: Result format: markdown, annotated, docling, json
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/process"
        response = self._http.upload("POST", path, file=file, file_name=file_name, field_name="file")
        return ProcessDocumentResponse.model_validate(response)

    def get_status(self, job_id: str) -> "DocumentStatus":
        """
        Get document parsing status
        
        Check the status of a document parsing job, including progress statistics.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/{job_id}"
        path = path.replace("{job_id}", str(job_id))
        response = self._http.request("GET", path)
        return DocumentStatus.model_validate(response)

    def get_result(self, job_id: str, format: Optional[str] = None) -> str:
        """
        Get parsed document result
        
        Download the parsed result of a completed document parsing job.
        
        Args:
            job_id: The job_id parameter
            format: Result format: markdown, annotated, docling, json
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/{job_id}/result"
        path = path.replace("{job_id}", str(job_id))
        params = {}
        if format is not None:
            params["format"] = format
        response = self._http.request("GET", path, params=params)
        return response

    def list_children(self, job_id: str) -> List["DocumentChild"]:
        """
        List child documents
        
        For container files (ZIP, TAR, EML), list the child documents extracted from the container.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/{job_id}/children"
        path = path.replace("{job_id}", str(job_id))
        response = self._http.request("GET", path)
        return [DocumentChild.model_validate(item) for item in response]

    def stream_trace(self, job_id: str) -> Iterator[Union["LayoutDetectedEvent", "TableExtractedEvent", "OcrPageEvent", "CompletedEvent", "ErrorEvent"]]:
        """
        Stream document parsing trace
        
        Subscribe to real-time parsing progress via Server-Sent Events.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/{job_id}/trace"
        path = path.replace("{job_id}", str(job_id))
        return self._http.stream("GET", path)

    def transform(self, body: "TransformDocumentRequest") -> "TransformDocumentResponse":
        """
        Transform a document using AI extraction (sync)
        
        Submit a document for AI-powered structured extraction and block until complete. Internally orchestrates a system agent session, polls for completion, and returns the extracted data.
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/transform"
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return TransformDocumentResponse.model_validate(response)

    def submit_transform(self, body: "TransformDocumentRequest") -> "SubmitDocumentTransformResponse":
        """
        Submit a document transform (async)
        
        Submit a document for AI-powered extraction and return immediately. Poll for completion via client.sessions.get(execution_id).
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/transform/submit"
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return SubmitDocumentTransformResponse.model_validate(response)


class AsyncDocumentsResource:
    """Parse and transform documents into structured data (async)"""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def parse(self, file: BinaryIO, file_name: str) -> "ParseDocumentResponse":
        """
        Parse a document (async)
        
        Upload a document for asynchronous parsing. Returns a job ID to track progress.
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents"
        response = await self._http.upload("POST", path, file=file, file_name=file_name, field_name="file")
        return ParseDocumentResponse.model_validate(response)

    async def process(self, file: BinaryIO, file_name: str) -> "ProcessDocumentResponse":
        """
        Parse a document (sync)
        
        Upload a document and block until parsing is complete. Returns the full parsed result.
        
        Args:
            format: Result format: markdown, annotated, docling, json
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/process"
        response = await self._http.upload("POST", path, file=file, file_name=file_name, field_name="file")
        return ProcessDocumentResponse.model_validate(response)

    async def get_status(self, job_id: str) -> "DocumentStatus":
        """
        Get document parsing status
        
        Check the status of a document parsing job, including progress statistics.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/{job_id}"
        path = path.replace("{job_id}", str(job_id))
        response = await self._http.request("GET", path)
        return DocumentStatus.model_validate(response)

    async def get_result(self, job_id: str, format: Optional[str] = None) -> str:
        """
        Get parsed document result
        
        Download the parsed result of a completed document parsing job.
        
        Args:
            job_id: The job_id parameter
            format: Result format: markdown, annotated, docling, json
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/{job_id}/result"
        path = path.replace("{job_id}", str(job_id))
        params = {}
        if format is not None:
            params["format"] = format
        response = await self._http.request("GET", path, params=params)
        return response

    async def list_children(self, job_id: str) -> List["DocumentChild"]:
        """
        List child documents
        
        For container files (ZIP, TAR, EML), list the child documents extracted from the container.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/{job_id}/children"
        path = path.replace("{job_id}", str(job_id))
        response = await self._http.request("GET", path)
        return [DocumentChild.model_validate(item) for item in response]

    async def stream_trace(self, job_id: str) -> AsyncIterator[Union["LayoutDetectedEvent", "TableExtractedEvent", "OcrPageEvent", "CompletedEvent", "ErrorEvent"]]:
        """
        Stream document parsing trace
        
        Subscribe to real-time parsing progress via Server-Sent Events.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/{job_id}/trace"
        path = path.replace("{job_id}", str(job_id))
        return self._http.stream("GET", path)

    async def transform(self, body: "TransformDocumentRequest") -> "TransformDocumentResponse":
        """
        Transform a document using AI extraction (sync)
        
        Submit a document for AI-powered structured extraction and block until complete. Internally orchestrates a system agent session, polls for completion, and returns the extracted data.
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/transform"
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return TransformDocumentResponse.model_validate(response)

    async def submit_transform(self, body: "TransformDocumentRequest") -> "SubmitDocumentTransformResponse":
        """
        Submit a document transform (async)
        
        Submit a document for AI-powered extraction and return immediately. Poll for completion via client.sessions.get(execution_id).
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/documents/transform/submit"
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return SubmitDocumentTransformResponse.model_validate(response)
