"""
Documents resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status
from .._streaming import SSEIterator, AsyncSSEIterator
from typing import BinaryIO


class DocumentsResource:
    """Parse and transform documents into structured data"""

    def __init__(self, http: HttpClient):
        self._http = http

    def parse_document(self, file: BinaryIO, file_name: str) -> "ParseDocumentResponse":
        """
        Parse a document (async)
        
        Upload a document for asynchronous parsing. Returns a job ID to track progress.
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/documents"
        response = self._http.upload("POST", path, file=file, file_name=file_name)
        return ParseDocumentResponse.model_validate(response)

    def process_document(self, file: BinaryIO, file_name: str) -> "ProcessDocumentResponse":
        """
        Parse a document (sync)
        
        Upload a document and block until parsing is complete. Returns the full parsed result.
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/documents/process"
        response = self._http.upload("POST", path, file=file, file_name=file_name)
        return ProcessDocumentResponse.model_validate(response)

    def get_document_status(self, job_id: str) -> "DocumentStatus":
        """
        Get document parsing status
        
        Check the status of a document parsing job, including progress statistics.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/documents/{job_id}"
        path = path.replace("{job_id}", str(job_id))
        response = self._http.request("GET", path)
        return DocumentStatus.model_validate(response)

    def get_document_result(self, job_id: str) -> str:
        """
        Get parsed document result
        
        Download the parsed result of a completed document parsing job.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/documents/{job_id}/result"
        path = path.replace("{job_id}", str(job_id))
        response = self._http.request("GET", path)
        return response

    def list_document_children(self, job_id: str) -> List["DocumentChild"]:
        """
        List child documents
        
        For container files (ZIP, TAR, EML), list the child documents extracted from the container.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/documents/{job_id}/children"
        path = path.replace("{job_id}", str(job_id))
        response = self._http.request("GET", path)
        return [DocumentChild.model_validate(item) for item in response]

    def stream_document_trace(self, job_id: str) -> Iterator[Union["", "", "", "", ""]]:
        """
        Stream document parsing trace
        
        Subscribe to real-time parsing progress via Server-Sent Events.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/documents/{job_id}/trace"
        path = path.replace("{job_id}", str(job_id))
        return self._http.stream("GET", path)


class AsyncDocumentsResource:
    """Parse and transform documents into structured data (async)"""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def parse_document(self, file: BinaryIO, file_name: str) -> "ParseDocumentResponse":
        """
        Parse a document (async)
        
        Upload a document for asynchronous parsing. Returns a job ID to track progress.
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/documents"
        response = await self._http.upload("POST", path, file=file, file_name=file_name)
        return ParseDocumentResponse.model_validate(response)

    async def process_document(self, file: BinaryIO, file_name: str) -> "ProcessDocumentResponse":
        """
        Parse a document (sync)
        
        Upload a document and block until parsing is complete. Returns the full parsed result.
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/documents/process"
        response = await self._http.upload("POST", path, file=file, file_name=file_name)
        return ProcessDocumentResponse.model_validate(response)

    async def get_document_status(self, job_id: str) -> "DocumentStatus":
        """
        Get document parsing status
        
        Check the status of a document parsing job, including progress statistics.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/documents/{job_id}"
        path = path.replace("{job_id}", str(job_id))
        response = await self._http.request("GET", path)
        return DocumentStatus.model_validate(response)

    async def get_document_result(self, job_id: str) -> str:
        """
        Get parsed document result
        
        Download the parsed result of a completed document parsing job.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/documents/{job_id}/result"
        path = path.replace("{job_id}", str(job_id))
        response = await self._http.request("GET", path)
        return response

    async def list_document_children(self, job_id: str) -> List["DocumentChild"]:
        """
        List child documents
        
        For container files (ZIP, TAR, EML), list the child documents extracted from the container.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/documents/{job_id}/children"
        path = path.replace("{job_id}", str(job_id))
        response = await self._http.request("GET", path)
        return [DocumentChild.model_validate(item) for item in response]

    async def stream_document_trace(self, job_id: str) -> AsyncIterator[Union["", "", "", "", ""]]:
        """
        Stream document parsing trace
        
        Subscribe to real-time parsing progress via Server-Sent Events.
        
        Args:
            job_id: The job_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/documents/{job_id}/trace"
        path = path.replace("{job_id}", str(job_id))
        return self._http.stream("GET", path)
