"""
Downloads resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status
from .._streaming import SSEIterator, AsyncSSEIterator


class DownloadsResource:
    """Export datasources as downloadable files"""

    def __init__(self, http: HttpClient):
        self._http = http

    def create_download_job(self, datasource_id: str, body: Optional[Union["DownloadJobRequest", None]] = None) -> "DownloadJobResponse":
        """
        Create Download Job (async)
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/downloads"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return DownloadJobResponse.model_validate(response)

    def stream_download_progress(self, datasource_id: str, job_id: str) -> Iterator[Union["", "", "", ""]]:
        """
        Stream Download Progress
        
        Args:
            datasource_id: The datasource_id parameter
            job_id: The job_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/downloads/{job_id}/progress"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{job_id}", str(job_id))
        return self._http.stream("GET", path)

    def download_file(self, datasource_id: str, job_id: str) -> str:
        """
        Download File
        
        Args:
            datasource_id: The datasource_id parameter
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/downloads/{job_id}/file"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{job_id}", str(job_id))
        response = self._http.request("GET", path)
        return response

    def process_download(self, datasource_id: str, body: Optional[Union["DownloadJobRequest", None]] = None) -> str:
        """
        Process Download (sync)
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/downloads/process"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return response


class AsyncDownloadsResource:
    """Export datasources as downloadable files (async)"""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def create_download_job(self, datasource_id: str, body: Optional[Union["DownloadJobRequest", None]] = None) -> "DownloadJobResponse":
        """
        Create Download Job (async)
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/downloads"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return DownloadJobResponse.model_validate(response)

    async def stream_download_progress(self, datasource_id: str, job_id: str) -> AsyncIterator[Union["", "", "", ""]]:
        """
        Stream Download Progress
        
        Args:
            datasource_id: The datasource_id parameter
            job_id: The job_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/downloads/{job_id}/progress"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{job_id}", str(job_id))
        return self._http.stream("GET", path)

    async def download_file(self, datasource_id: str, job_id: str) -> str:
        """
        Download File
        
        Args:
            datasource_id: The datasource_id parameter
            job_id: The job_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/downloads/{job_id}/file"
        path = path.replace("{datasource_id}", str(datasource_id))
        path = path.replace("{job_id}", str(job_id))
        response = await self._http.request("GET", path)
        return response

    async def process_download(self, datasource_id: str, body: Optional[Union["DownloadJobRequest", None]] = None) -> str:
        """
        Process Download (sync)
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/downloads/process"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return response
