"""
Executions resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status


class ExecutionsResource:
    """Run, monitor, and manage batch executions"""

    def __init__(self, http: HttpClient):
        self._http = http

    def list(self, input_datasource_id: Optional[Union[str, None]] = None, offset: Optional[int] = None, limit: Optional[Union[int, None]] = None, sort_by: Optional[str] = None, sort_order: Optional[str] = None) -> "GetBatchExecutionsResponse":
        """
        List Batch Executions
        
        Args:
            input_datasource_id: Filter by input datasource ID
            offset: The offset parameter
            limit: The limit parameter
            sort_by: Field to sort by: start_time, status
            sort_order: The sort_order parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-executions"
        params: Dict[str, Any] = {}
        if input_datasource_id is not None:
            params["input_datasource_id"] = input_datasource_id
        if offset is not None:
            params["offset"] = offset
        if limit is not None:
            params["limit"] = limit
        if sort_by is not None:
            params["sort_by"] = sort_by
        if sort_order is not None:
            params["sort_order"] = sort_order
        response = self._http.request("GET", path, params=params)
        return GetBatchExecutionsResponse.model_validate(response)

    def create(self, body: "CreateBatchExecutionRequest") -> "BatchExecutionResponse":
        """
        Create Batch Execution
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-executions"
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return BatchExecutionResponse.model_validate(response)

    def get_by_id(self, execution_id: str) -> "BatchExecutionResponse":
        """
        Get Batch Execution By Id
        
        Args:
            execution_id: The execution_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-executions/id/{execution_id}"
        path = path.replace("{execution_id}", str(execution_id))
        response = self._http.request("GET", path)
        return BatchExecutionResponse.model_validate(response)

    def update_by_id(self, execution_id: str, body: "UpdateBatchExecutionRequest") -> "BatchExecutionResponse":
        """
        Update Batch Execution By Id
        
        Args:
            execution_id: The execution_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-executions/id/{execution_id}"
        path = path.replace("{execution_id}", str(execution_id))
        response = self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return BatchExecutionResponse.model_validate(response)

    def get_realtime_progress(self, execution_id: str) -> str:
        """
        Get Batch Realtime Progress
        
        Args:
            execution_id: The execution_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-executions/id/{execution_id}/realtime-progress"
        path = path.replace("{execution_id}", str(execution_id))
        response = self._http.request("GET", path)
        return response

    def retry_failed_items(self, execution_id: str) -> "BatchExecutionResponse":
        """
        Retry Failed Items
        
        Args:
            execution_id: The execution_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-executions/id/{execution_id}/retry-failed"
        path = path.replace("{execution_id}", str(execution_id))
        response = self._http.request("POST", path)
        return BatchExecutionResponse.model_validate(response)

    def cancel(self, execution_id: str) -> "BatchExecutionResponse":
        """
        Cancel Batch Execution
        
        Args:
            execution_id: The execution_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-executions/id/{execution_id}/cancel"
        path = path.replace("{execution_id}", str(execution_id))
        response = self._http.request("POST", path)
        return BatchExecutionResponse.model_validate(response)


class AsyncExecutionsResource:
    """Run, monitor, and manage batch executions (async)"""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def list(self, input_datasource_id: Optional[Union[str, None]] = None, offset: Optional[int] = None, limit: Optional[Union[int, None]] = None, sort_by: Optional[str] = None, sort_order: Optional[str] = None) -> "GetBatchExecutionsResponse":
        """
        List Batch Executions
        
        Args:
            input_datasource_id: Filter by input datasource ID
            offset: The offset parameter
            limit: The limit parameter
            sort_by: Field to sort by: start_time, status
            sort_order: The sort_order parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-executions"
        params: Dict[str, Any] = {}
        if input_datasource_id is not None:
            params["input_datasource_id"] = input_datasource_id
        if offset is not None:
            params["offset"] = offset
        if limit is not None:
            params["limit"] = limit
        if sort_by is not None:
            params["sort_by"] = sort_by
        if sort_order is not None:
            params["sort_order"] = sort_order
        response = await self._http.request("GET", path, params=params)
        return GetBatchExecutionsResponse.model_validate(response)

    async def create(self, body: "CreateBatchExecutionRequest") -> "BatchExecutionResponse":
        """
        Create Batch Execution
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-executions"
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return BatchExecutionResponse.model_validate(response)

    async def get_by_id(self, execution_id: str) -> "BatchExecutionResponse":
        """
        Get Batch Execution By Id
        
        Args:
            execution_id: The execution_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-executions/id/{execution_id}"
        path = path.replace("{execution_id}", str(execution_id))
        response = await self._http.request("GET", path)
        return BatchExecutionResponse.model_validate(response)

    async def update_by_id(self, execution_id: str, body: "UpdateBatchExecutionRequest") -> "BatchExecutionResponse":
        """
        Update Batch Execution By Id
        
        Args:
            execution_id: The execution_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-executions/id/{execution_id}"
        path = path.replace("{execution_id}", str(execution_id))
        response = await self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return BatchExecutionResponse.model_validate(response)

    async def get_realtime_progress(self, execution_id: str) -> str:
        """
        Get Batch Realtime Progress
        
        Args:
            execution_id: The execution_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-executions/id/{execution_id}/realtime-progress"
        path = path.replace("{execution_id}", str(execution_id))
        response = await self._http.request("GET", path)
        return response

    async def retry_failed_items(self, execution_id: str) -> "BatchExecutionResponse":
        """
        Retry Failed Items
        
        Args:
            execution_id: The execution_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-executions/id/{execution_id}/retry-failed"
        path = path.replace("{execution_id}", str(execution_id))
        response = await self._http.request("POST", path)
        return BatchExecutionResponse.model_validate(response)

    async def cancel(self, execution_id: str) -> "BatchExecutionResponse":
        """
        Cancel Batch Execution
        
        Args:
            execution_id: The execution_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/batch-executions/id/{execution_id}/cancel"
        path = path.replace("{execution_id}", str(execution_id))
        response = await self._http.request("POST", path)
        return BatchExecutionResponse.model_validate(response)
