"""
ExecutionPolicies resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status


class ExecutionPoliciesResource:
    """Manage execution policies"""

    def __init__(self, http: HttpClient):
        self._http = http

    def list(self) -> "GetExecutionPoliciesResponse":
        """
        List Execution Policies
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/execution-policies"
        response = self._http.request("GET", path)
        return GetExecutionPoliciesResponse.model_validate(response)

    def create(self, body: "CreateExecutionPolicyRequest") -> "ExecutionPolicyResponse":
        """
        Create Execution Policy
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/execution-policies"
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return ExecutionPolicyResponse.model_validate(response)

    def get(self, policy_id: str) -> "ExecutionPolicyResponse":
        """
        Get Execution Policy
        
        Args:
            policy_id: The policy_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/execution-policies/{policy_id}"
        path = path.replace("{policy_id}", str(policy_id))
        response = self._http.request("GET", path)
        return ExecutionPolicyResponse.model_validate(response)

    def update(self, policy_id: str, body: "UpdateExecutionPolicyRequest") -> "ExecutionPolicyResponse":
        """
        Update Execution Policy
        
        Args:
            policy_id: The policy_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/execution-policies/{policy_id}"
        path = path.replace("{policy_id}", str(policy_id))
        response = self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return ExecutionPolicyResponse.model_validate(response)

    def delete(self, policy_id: str) -> None:
        """
        Delete Execution Policy
        
        Args:
            policy_id: The policy_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/execution-policies/{policy_id}"
        path = path.replace("{policy_id}", str(policy_id))
        response = self._http.request("DELETE", path)
        return response


class AsyncExecutionPoliciesResource:
    """Manage execution policies (async)"""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def list(self) -> "GetExecutionPoliciesResponse":
        """
        List Execution Policies
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/execution-policies"
        response = await self._http.request("GET", path)
        return GetExecutionPoliciesResponse.model_validate(response)

    async def create(self, body: "CreateExecutionPolicyRequest") -> "ExecutionPolicyResponse":
        """
        Create Execution Policy
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/execution-policies"
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return ExecutionPolicyResponse.model_validate(response)

    async def get(self, policy_id: str) -> "ExecutionPolicyResponse":
        """
        Get Execution Policy
        
        Args:
            policy_id: The policy_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/execution-policies/{policy_id}"
        path = path.replace("{policy_id}", str(policy_id))
        response = await self._http.request("GET", path)
        return ExecutionPolicyResponse.model_validate(response)

    async def update(self, policy_id: str, body: "UpdateExecutionPolicyRequest") -> "ExecutionPolicyResponse":
        """
        Update Execution Policy
        
        Args:
            policy_id: The policy_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/execution-policies/{policy_id}"
        path = path.replace("{policy_id}", str(policy_id))
        response = await self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return ExecutionPolicyResponse.model_validate(response)

    async def delete(self, policy_id: str) -> None:
        """
        Delete Execution Policy
        
        Args:
            policy_id: The policy_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/execution-policies/{policy_id}"
        path = path.replace("{policy_id}", str(policy_id))
        response = await self._http.request("DELETE", path)
        return response
