"""
FileUploads resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status
from .._pagination import PaginatedIterator, AsyncPaginatedIterator
from .._streaming import SSEIterator, AsyncSSEIterator
from typing import BinaryIO


class FileUploadsResource:
    """Upload and manage content files"""

    def __init__(self, http: HttpClient):
        self._http = http

    def upload_content(self, files: BinaryIO, files_name: str, datasource_id: Optional[str] = None, name: Optional[str] = None, description: Optional[str] = None, metadata_config: Optional["MetadataConfigRequest"] = None) -> "UploadContentResponse":
        """
        Upload Content (async)
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/uploads"
        form_fields = {}
        if datasource_id is not None:
            form_fields["datasource_id"] = str(datasource_id)
        if name is not None:
            form_fields["name"] = str(name)
        if description is not None:
            form_fields["description"] = str(description)
        if metadata_config is not None:
            form_fields["metadata_config"] = str(metadata_config)
        response = self._http.upload("POST", path, file=files, file_name=files_name, field_name="files", form_fields=form_fields)
        return UploadContentResponse.model_validate(response)

    def upload_and_list_content(self, files: BinaryIO, files_name: str, datasource_id: Optional[str] = None, name: Optional[str] = None, description: Optional[str] = None, metadata_config: Optional["MetadataConfigRequest"] = None, trigger_ingest: Optional[bool] = None) -> "FileUploadSyncResponse":
        """
        Upload Content (sync)
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/uploads/process"
        form_fields = {}
        if datasource_id is not None:
            form_fields["datasource_id"] = str(datasource_id)
        if name is not None:
            form_fields["name"] = str(name)
        if description is not None:
            form_fields["description"] = str(description)
        if metadata_config is not None:
            form_fields["metadata_config"] = str(metadata_config)
        if trigger_ingest is not None:
            form_fields["trigger_ingest"] = str(trigger_ingest)
        response = self._http.upload("POST", path, file=files, file_name=files_name, field_name="files", form_fields=form_fields)
        return FileUploadSyncResponse.model_validate(response)

    def stream_upload_progress(self, upload_id: str) -> Iterator[Union["ConnectedEvent", "ProgressEvent", "StreamCompleteEvent", "ErrorEvent"]]:
        """
        Stream Upload Progress
        
        Args:
            upload_id: The upload_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/uploads/{upload_id}/progress"
        path = path.replace("{upload_id}", str(upload_id))
        return self._http.stream("GET", path)

    def list_content(self, datasource_id: str, prefix: Optional[Union[str, None]] = None, continuation_token: Optional[Union[str, None]] = None, limit: Optional[int] = None) -> PaginatedIterator["ContentItem"]:
        """
        List Content
        
        Args:
            datasource_id: The datasource_id parameter
            prefix: Filter content by path prefix
            continuation_token: Token for pagination
            limit: Maximum items to return
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/content"
        path = path.replace("{datasource_id}", str(datasource_id))
        params = {}
        if prefix is not None:
            params["prefix"] = prefix
        if continuation_token is not None:
            params["continuation_token"] = continuation_token
        if limit is not None:
            params["limit"] = limit
        return PaginatedIterator(
            self._http,
            "GET",
            path,
            items_field="items",
            cursor_param="continuation_token",
            next_field="next_cursor",
            params=params,
        )


class AsyncFileUploadsResource:
    """Upload and manage content files (async)"""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def upload_content(self, files: BinaryIO, files_name: str, datasource_id: Optional[str] = None, name: Optional[str] = None, description: Optional[str] = None, metadata_config: Optional["MetadataConfigRequest"] = None) -> "UploadContentResponse":
        """
        Upload Content (async)
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/uploads"
        form_fields = {}
        if datasource_id is not None:
            form_fields["datasource_id"] = str(datasource_id)
        if name is not None:
            form_fields["name"] = str(name)
        if description is not None:
            form_fields["description"] = str(description)
        if metadata_config is not None:
            form_fields["metadata_config"] = str(metadata_config)
        response = await self._http.upload("POST", path, file=files, file_name=files_name, field_name="files", form_fields=form_fields)
        return UploadContentResponse.model_validate(response)

    async def upload_and_list_content(self, files: BinaryIO, files_name: str, datasource_id: Optional[str] = None, name: Optional[str] = None, description: Optional[str] = None, metadata_config: Optional["MetadataConfigRequest"] = None, trigger_ingest: Optional[bool] = None) -> "FileUploadSyncResponse":
        """
        Upload Content (sync)
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/uploads/process"
        form_fields = {}
        if datasource_id is not None:
            form_fields["datasource_id"] = str(datasource_id)
        if name is not None:
            form_fields["name"] = str(name)
        if description is not None:
            form_fields["description"] = str(description)
        if metadata_config is not None:
            form_fields["metadata_config"] = str(metadata_config)
        if trigger_ingest is not None:
            form_fields["trigger_ingest"] = str(trigger_ingest)
        response = await self._http.upload("POST", path, file=files, file_name=files_name, field_name="files", form_fields=form_fields)
        return FileUploadSyncResponse.model_validate(response)

    async def stream_upload_progress(self, upload_id: str) -> AsyncIterator[Union["ConnectedEvent", "ProgressEvent", "StreamCompleteEvent", "ErrorEvent"]]:
        """
        Stream Upload Progress
        
        Args:
            upload_id: The upload_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/uploads/{upload_id}/progress"
        path = path.replace("{upload_id}", str(upload_id))
        return self._http.stream("GET", path)

    async def list_content(self, datasource_id: str, prefix: Optional[Union[str, None]] = None, continuation_token: Optional[Union[str, None]] = None, limit: Optional[int] = None) -> AsyncPaginatedIterator["ContentItem"]:
        """
        List Content
        
        Args:
            datasource_id: The datasource_id parameter
            prefix: Filter content by path prefix
            continuation_token: Token for pagination
            limit: Maximum items to return
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/datasources/{datasource_id}/content"
        path = path.replace("{datasource_id}", str(datasource_id))
        params = {}
        if prefix is not None:
            params["prefix"] = prefix
        if continuation_token is not None:
            params["continuation_token"] = continuation_token
        if limit is not None:
            params["limit"] = limit
        return AsyncPaginatedIterator(
            self._http,
            "GET",
            path,
            items_field="items",
            cursor_param="continuation_token",
            next_field="next_cursor",
            params=params,
        )
