"""
Metadata Configuration resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status


class MetadataConfigurationResource:
    """Metadata Configuration resource operations."""

    def __init__(self, http: HttpClient):
        self._http = http

    def get_metadata_config(self, datasource_id: str) -> "MetadataConfigResponse":
        """
        Get Metadata Config
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/datasources/{datasource_id}/metadata-config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("GET", path)
        return MetadataConfigResponse.model_validate(response)

    def update_metadata_config(self, datasource_id: str, body: "MetadataConfigRequest") -> "MetadataConfigResponse":
        """
        Update Metadata Config
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/datasources/{datasource_id}/metadata-config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return MetadataConfigResponse.model_validate(response)

    def reprocess_metadata(self, datasource_id: str) -> str:
        """
        Reprocess Metadata
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/datasources/{datasource_id}/reprocess-metadata"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("POST", path)
        return response

    def get_reprocess_metadata_status(self, datasource_id: str) -> str:
        """
        Get Reprocess Metadata Status
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/datasources/{datasource_id}/reprocess-metadata/status"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = self._http.request("GET", path)
        return response


class AsyncMetadataConfigurationResource:
    """Metadata Configuration resource operations (async)."""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def get_metadata_config(self, datasource_id: str) -> "MetadataConfigResponse":
        """
        Get Metadata Config
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/datasources/{datasource_id}/metadata-config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("GET", path)
        return MetadataConfigResponse.model_validate(response)

    async def update_metadata_config(self, datasource_id: str, body: "MetadataConfigRequest") -> "MetadataConfigResponse":
        """
        Update Metadata Config
        
        Args:
            datasource_id: The datasource_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/datasources/{datasource_id}/metadata-config"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return MetadataConfigResponse.model_validate(response)

    async def reprocess_metadata(self, datasource_id: str) -> str:
        """
        Reprocess Metadata
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/datasources/{datasource_id}/reprocess-metadata"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("POST", path)
        return response

    async def get_reprocess_metadata_status(self, datasource_id: str) -> str:
        """
        Get Reprocess Metadata Status
        
        Args:
            datasource_id: The datasource_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/v2/datasources/{datasource_id}/reprocess-metadata/status"
        path = path.replace("{datasource_id}", str(datasource_id))
        response = await self._http.request("GET", path)
        return response
