"""
Metadata Model Catalog resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status


class MetadataModelCatalogResource:
    """Metadata Model Catalog resource operations."""

    def __init__(self, http: HttpClient):
        self._http = http

    def list_metadata_model_catalog(self, scope: Optional[Union[str, None]] = None) -> "ListMetadataModelCatalogResponse":
        """
        List Metadata Model Catalog
        
        Args:
            scope: The scope parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/metadata-model-catalog"
        params = {}
        if scope is not None:
            params["scope"] = scope
        response = self._http.request("GET", path, params=params)
        return ListMetadataModelCatalogResponse.model_validate(response)

    def get_metadata_model_catalog_entry(self, model_id: str) -> "MetadataModelCatalogEntry":
        """
        Get Metadata Model Catalog Entry
        
        Args:
            model_id: The model_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/metadata-model-catalog/{model_id}"
        path = path.replace("{model_id}", str(model_id))
        response = self._http.request("GET", path)
        return MetadataModelCatalogEntry.model_validate(response)


class AsyncMetadataModelCatalogResource:
    """Metadata Model Catalog resource operations (async)."""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def list_metadata_model_catalog(self, scope: Optional[Union[str, None]] = None) -> "ListMetadataModelCatalogResponse":
        """
        List Metadata Model Catalog
        
        Args:
            scope: The scope parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/metadata-model-catalog"
        params = {}
        if scope is not None:
            params["scope"] = scope
        response = await self._http.request("GET", path, params=params)
        return ListMetadataModelCatalogResponse.model_validate(response)

    async def get_metadata_model_catalog_entry(self, model_id: str) -> "MetadataModelCatalogEntry":
        """
        Get Metadata Model Catalog Entry
        
        Args:
            model_id: The model_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/metadata-model-catalog/{model_id}"
        path = path.replace("{model_id}", str(model_id))
        response = await self._http.request("GET", path)
        return MetadataModelCatalogEntry.model_validate(response)
