"""
Prompts resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status


class PromptsResource:
    """Manage reusable prompt templates"""

    def __init__(self, http: HttpClient):
        self._http = http

    def list_prompts(self) -> "PromptListResponse":
        """
        List Prompts
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/prompts/"
        response = self._http.request("GET", path)
        return PromptListResponse.model_validate(response)

    def create_prompt(self, body: "CreateAgentPromptRequest") -> "CreatePromptResponse":
        """
        Create Prompt
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/prompts/"
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return CreatePromptResponse.model_validate(response)

    def get_prompt(self, prompt_id: str) -> "PromptResponse":
        """
        Get Prompt
        
        Args:
            prompt_id: The prompt_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/prompts/{prompt_id}"
        path = path.replace("{prompt_id}", str(prompt_id))
        response = self._http.request("GET", path)
        return PromptResponse.model_validate(response)

    def update_prompt(self, prompt_id: str, body: "UpdateAgentPromptRequest") -> "UpdatePromptResponse":
        """
        Update Prompt
        
        Args:
            prompt_id: The prompt_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/prompts/{prompt_id}"
        path = path.replace("{prompt_id}", str(prompt_id))
        response = self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return UpdatePromptResponse.model_validate(response)

    def delete_prompt(self, prompt_id: str) -> None:
        """
        Delete Prompt
        
        Args:
            prompt_id: The prompt_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/prompts/{prompt_id}"
        path = path.replace("{prompt_id}", str(prompt_id))
        response = self._http.request("DELETE", path)
        return response


class AsyncPromptsResource:
    """Manage reusable prompt templates (async)"""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def list_prompts(self) -> "PromptListResponse":
        """
        List Prompts
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/prompts/"
        response = await self._http.request("GET", path)
        return PromptListResponse.model_validate(response)

    async def create_prompt(self, body: "CreateAgentPromptRequest") -> "CreatePromptResponse":
        """
        Create Prompt
        
        Args:
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/prompts/"
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return CreatePromptResponse.model_validate(response)

    async def get_prompt(self, prompt_id: str) -> "PromptResponse":
        """
        Get Prompt
        
        Args:
            prompt_id: The prompt_id parameter
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/prompts/{prompt_id}"
        path = path.replace("{prompt_id}", str(prompt_id))
        response = await self._http.request("GET", path)
        return PromptResponse.model_validate(response)

    async def update_prompt(self, prompt_id: str, body: "UpdateAgentPromptRequest") -> "UpdatePromptResponse":
        """
        Update Prompt
        
        Args:
            prompt_id: The prompt_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/prompts/{prompt_id}"
        path = path.replace("{prompt_id}", str(prompt_id))
        response = await self._http.request("PUT", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return UpdatePromptResponse.model_validate(response)

    async def delete_prompt(self, prompt_id: str) -> None:
        """
        Delete Prompt
        
        Args:
            prompt_id: The prompt_id parameter
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/prompts/{prompt_id}"
        path = path.replace("{prompt_id}", str(prompt_id))
        response = await self._http.request("DELETE", path)
        return response
