"""
Sessions resource operations.

Generated by Forge SDK Generator.
"""

from typing import Optional, List, Dict, Any, Union, Iterator, AsyncIterator
from .._http import HttpClient, AsyncHttpClient
from ..models import *
from ..exceptions import raise_for_status


class SessionsResource:
    """Interact with agent sessions via chat"""

    def __init__(self, http: HttpClient):
        self._http = http

    def send_chat_message(self, blueprint_instance_id: str, body: "ChatMessageRequest") -> "ChatMessageResponse":
        """
        Send Chat Message
        
        Args:
            blueprint_instance_id: The blueprint_instance_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/{blueprint_instance_id}/chat"
        path = path.replace("{blueprint_instance_id}", str(blueprint_instance_id))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return ChatMessageResponse.model_validate(response)

    def send_chat_message_stream(self, blueprint_instance_id: str, body: "ChatMessageRequest") -> None:
        """
        Send a chat message and stream the response via SSE
        
        Send a chat message to a running chat agent workflow and stream the response as Server-Sent Events.
        
        Args:
            blueprint_instance_id: The blueprint_instance_id parameter
            body: Request body
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/{blueprint_instance_id}/chat/stream"
        path = path.replace("{blueprint_instance_id}", str(blueprint_instance_id))
        response = self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return response


class AsyncSessionsResource:
    """Interact with agent sessions via chat (async)"""

    def __init__(self, http: AsyncHttpClient):
        self._http = http

    async def send_chat_message(self, blueprint_instance_id: str, body: "ChatMessageRequest") -> "ChatMessageResponse":
        """
        Send Chat Message
        
        Args:
            blueprint_instance_id: The blueprint_instance_id parameter
            body: Request body
        
        Returns:
            Successful Response
        
        Raises:
            ApiError: If the request fails
        """
        path = "/{blueprint_instance_id}/chat"
        path = path.replace("{blueprint_instance_id}", str(blueprint_instance_id))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return ChatMessageResponse.model_validate(response)

    async def send_chat_message_stream(self, blueprint_instance_id: str, body: "ChatMessageRequest") -> None:
        """
        Send a chat message and stream the response via SSE
        
        Send a chat message to a running chat agent workflow and stream the response as Server-Sent Events.
        
        Args:
            blueprint_instance_id: The blueprint_instance_id parameter
            body: Request body
        
        Returns:
            None
        
        Raises:
            ApiError: If the request fails
        """
        path = "/{blueprint_instance_id}/chat/stream"
        path = path.replace("{blueprint_instance_id}", str(blueprint_instance_id))
        response = await self._http.request("POST", path, json=body.model_dump(by_alias=True, exclude_unset=True) if body else None)
        return response
