"""
meibel-ai-api - The Meibel API provides document parsing, datasource management, and AI agent orchestration. Read the docs at https://docs.meibel.ai to learn more.

Generated by Forge SDK Generator.
"""

__version__ = "0.4.0"

from .client import MeibelClient
from .client import AsyncMeibelClient
from .models import *
from .exceptions import *
from ._metadata import metadata_schema_from_model
from ._artifacts import artifact_schema_from_model
from ._system_agents import transform_document, transform_document_async, submit_document_transform, submit_document_transform_async

__all__ = [
    "MeibelClient",
    "AsyncMeibelClient",
    "metadata_schema_from_model",
    "artifact_schema_from_model",
    "transform_document",
    "transform_document_async",
    "submit_document_transform",
    "submit_document_transform_async",
    "__version__",
]
