"""
meibel - The Meibel API provides document parsing, datasource management, and AI agent orchestration.

Generated by Forge SDK Generator.
"""

__version__ = "0.1.0-beta.1"

from .client import MeibelClient
from .client import AsyncMeibelClient
from .models import *
from .exceptions import *

__all__ = [
    "MeibelClient",
    "AsyncMeibelClient",
    "__version__",
]
