"""
Metadata schema helpers.

Converts native Pydantic models into MetadataConfigRequest dicts,
so users can define extraction schemas as plain Python classes.

Generated by Forge SDK Generator.
"""

from __future__ import annotations

import datetime
import typing
import uuid
from typing import Any, Dict, List, Optional, Type, cast, get_type_hints

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Type mapping: Python annotation -> Meibel metadata field type string
# ---------------------------------------------------------------------------

_PYTHON_TO_MEIBEL_TYPE: Dict[Any, str] = {
    str: "string",
    int: "integer",
    float: "float",
    bool: "boolean",
    datetime.datetime: "datetime",
    datetime.date: "datetime",
    uuid.UUID: "uuid",
}


def _resolve_meibel_type(annotation: Any) -> Optional[str]:
    """Map a Python type annotation to a Meibel metadata field type string."""
    # Direct match
    if annotation in _PYTHON_TO_MEIBEL_TYPE:
        return _PYTHON_TO_MEIBEL_TYPE[annotation]

    # Handle list[str] / List[str]
    origin = getattr(annotation, "__origin__", None)
    if origin is list or origin is typing.List:
        args = getattr(annotation, "__args__", ())
        if args and args[0] is str:
            return "list[string]"

    return None


def _get_field_description(model_cls: Type[BaseModel], field_name: str) -> str:
    """Extract the Field description for a model field, falling back to the field name."""
    field_info = model_cls.model_fields.get(field_name)
    if field_info and field_info.description:
        return field_info.description
    # Convert snake_case field name to a readable sentence
    return field_name.replace("_", " ")


def _get_field_index(model_cls: Type[BaseModel], field_name: str) -> bool:
    """Check if a field has index=False in its json_schema_extra or metadata, default True."""
    field_info = model_cls.model_fields.get(field_name)
    if field_info and field_info.json_schema_extra and isinstance(field_info.json_schema_extra, dict):
        return cast(bool, field_info.json_schema_extra.get("index", True))
    return True


def metadata_schema_from_model(
    model_cls: Type[BaseModel],
) -> Dict[str, Any]:
    """Convert a Pydantic BaseModel class into a MetadataConfigRequest dict.

    Usage::

        class InvoiceMetadata(BaseModel):
            vendor_name: str = Field(description="Name of the vendor")
            total_amount: float = Field(description="Invoice total")
            due_date: datetime.datetime = Field(description="Payment due date")
            line_items: list[str] = Field(description="Extracted line item descriptions")

        datasource = client.datasources.create(
            name="Invoices",
            connector=ConnectorConfig(type="cloud_storage", ...),
            metadata_config=metadata_schema_from_model(InvoiceMetadata),
        )

    Args:
        model_cls: A Pydantic BaseModel subclass whose fields define the
            metadata schema. Each field's Python type is mapped to a Meibel
            metadata field type. Use ``Field(description=...)`` to set the
            field description. To disable indexing on a field, use
            ``Field(json_schema_extra={"index": False})``.

    Returns:
        A dict matching the MetadataConfigRequest shape::

            {
                "type": "custom",
                "fields": [
                    {"name": "vendor_name", "type": "string", "description": "...", "index": True},
                    ...
                ]
            }

    Raises:
        TypeError: If a field's type cannot be mapped to a Meibel metadata type.
    """
    hints = get_type_hints(model_cls)
    fields: List[Dict[str, Any]] = []

    for field_name, annotation in hints.items():
        meibel_type = _resolve_meibel_type(annotation)
        if meibel_type is None:
            raise TypeError(
                f"Cannot map Python type {annotation!r} on field "
                f"'{model_cls.__name__}.{field_name}' to a Meibel metadata type. "
                f"Supported types: str, int, float, bool, datetime.datetime, "
                f"datetime.date, uuid.UUID, list[str]"
            )
        fields.append(
            {
                "name": field_name,
                "type": meibel_type,
                "description": _get_field_description(model_cls, field_name),
                "index": _get_field_index(model_cls, field_name),
            }
        )

    return {
        "type": "custom",
        "fields": fields,
    }