"""
System Agent Helpers

Convenience functions for system-agent one-liners that accept
language-native typed objects (Pydantic models) or artifact schema IDs
and handle schema conversion automatically.

Generated by Forge SDK Generator.
"""

from typing import Any, Dict, Optional, Type, Union

from pydantic import BaseModel


def _resolve_schema(schema: Union[str, Dict[str, Any], Type[BaseModel]]) -> Union[str, Dict[str, Any]]:
    """Resolve a schema argument to a value suitable for artifact_schema.

    Accepts:
      - A Pydantic BaseModel subclass → converted to JSON Schema dict
      - A dict → passed through as a raw JSON Schema
      - A string artifact schema ID → passed through as-is
    """
    if isinstance(schema, str):
        return schema
    if isinstance(schema, dict):
        return schema
    if isinstance(schema, type) and issubclass(schema, BaseModel):
        return schema.model_json_schema()
    raise TypeError(
        f"schema must be a Pydantic BaseModel subclass, a dict (JSON Schema), "
        f"or a string artifact schema ID, got {type(schema).__name__}"
    )


def transform_document(
    client,
    *,
    file: str,
    schema: Union[str, Dict[str, Any], Type[BaseModel]],
    model: Optional[str] = None,
    prompt: Optional[str] = None,
    prompt_id: Optional[str] = None,
    timeout_seconds: int = 600,
):
    """Transform a document using a Pydantic model, JSON Schema dict, or artifact schema ID.

    Calls the sync ``client.documents.transform()`` endpoint. When a Pydantic
    model is provided, it is automatically converted to a JSON Schema for the
    artifact_schema field. A dict is passed through as a raw JSON Schema.
    A string is passed through as an artifact schema ID.

    Example with a Pydantic model::

        from pydantic import BaseModel, Field

        class InvoiceOutput(BaseModel):
            vendor_name: str = Field(description="Name of the vendor")
            total_amount: float = Field(description="Invoice total")

        result = transform_document(client, file="invoice.pdf", schema=InvoiceOutput)
        print(result.data["vendor_name"])

    Example with a JSON Schema dict::

        schema = {"type": "object", "properties": {"vendor_name": {"type": "string"}}}
        result = transform_document(client, file="invoice.pdf", schema=schema)

    Example with an artifact schema ID::

        result = transform_document(client, file="invoice.pdf", schema="artifact-schema-id-123")

    Args:
        client: The SDK client instance.
        file: File path, URL, or GCS URI.
        schema: A Pydantic BaseModel subclass, a dict (JSON Schema), or artifact schema ID string.
        model: Optional LLM model override.
        prompt: Optional extraction instructions override.
        prompt_id: Optional prompt template reference.
        timeout_seconds: Max wait time (default 600s).

    Returns:
        TransformDocumentResponse with execution_id, data, and token_usage.
    """
    from .models import TransformDocumentRequest

    return client.documents.transform(body=TransformDocumentRequest(
        file=file,
        artifact_schema=_resolve_schema(schema),
        model=model,
        prompt=prompt,
        prompt_id=prompt_id,
        timeout_seconds=timeout_seconds,
    ))


def submit_document_transform(
    client,
    *,
    file: str,
    schema: Union[str, Dict[str, Any], Type[BaseModel]],
    model: Optional[str] = None,
    prompt: Optional[str] = None,
    prompt_id: Optional[str] = None,
):
    """Submit an async document transform using a Pydantic model, JSON Schema dict, or artifact schema ID.

    Returns immediately with an execution_id. Poll for completion via
    ``client.sessions.get(execution_id)``.

    Example::

        job = submit_document_transform(client, file="invoice.pdf", schema=InvoiceOutput)
        # ... do other work ...
        session = client.sessions.get(job.execution_id)

    Args:
        client: The SDK client instance.
        file: File path, URL, or GCS URI.
        schema: A Pydantic BaseModel subclass, a dict (JSON Schema), or artifact schema ID string.
        model: Optional LLM model override.
        prompt: Optional extraction instructions override.
        prompt_id: Optional prompt template reference.

    Returns:
        SubmitDocumentTransformResponse with execution_id.
    """
    from .models import TransformDocumentRequest

    return client.documents.submit_transform(body=TransformDocumentRequest(
        file=file,
        artifact_schema=_resolve_schema(schema),
        model=model,
        prompt=prompt,
        prompt_id=prompt_id,
    ))


async def transform_document_async(
    client,
    *,
    file: str,
    schema: Union[str, Dict[str, Any], Type[BaseModel]],
    model: Optional[str] = None,
    prompt: Optional[str] = None,
    prompt_id: Optional[str] = None,
    timeout_seconds: int = 600,
):
    """Async version of :func:`transform_document`.

    Use with :class:`AsyncMeibelClient`::

        from meibel import AsyncMeibelClient, transform_document_async

        client = AsyncMeibelClient(api_key="...")
        result = await transform_document_async(client, file="invoice.pdf", schema=InvoiceOutput)
    """
    from .models import TransformDocumentRequest

    return await client.documents.transform(body=TransformDocumentRequest(
        file=file,
        artifact_schema=_resolve_schema(schema),
        model=model,
        prompt=prompt,
        prompt_id=prompt_id,
        timeout_seconds=timeout_seconds,
    ))


async def submit_document_transform_async(
    client,
    *,
    file: str,
    schema: Union[str, Dict[str, Any], Type[BaseModel]],
    model: Optional[str] = None,
    prompt: Optional[str] = None,
    prompt_id: Optional[str] = None,
):
    """Async version of :func:`submit_document_transform`.

    Use with :class:`AsyncMeibelClient`::

        from meibel import AsyncMeibelClient, submit_document_transform_async

        client = AsyncMeibelClient(api_key="...")
        job = await submit_document_transform_async(client, file="invoice.pdf", schema=InvoiceOutput)
    """
    from .models import TransformDocumentRequest

    return await client.documents.submit_transform(body=TransformDocumentRequest(
        file=file,
        artifact_schema=_resolve_schema(schema),
        model=model,
        prompt=prompt,
        prompt_id=prompt_id,
    ))
