"""
Streaming multipart/form-data upload utilities.

Files are streamed in chunks — never fully buffered in memory.

Generated by Forge SDK Generator.
"""

from __future__ import annotations

import uuid
from typing import Any, AsyncIterator, Dict, Iterator, Optional, Tuple


def _generate_boundary() -> str:
    return f"----FormBoundary{uuid.uuid4().hex}"


def create_multipart_stream(
    file: Any,
    field_name: str = "file",
    file_name: str = "file",
    form_fields: Optional[Dict[str, str]] = None,
    chunk_size: int = 65536,
) -> Tuple[Iterator[bytes], str]:
    """Create a sync streaming multipart body.

    Args:
        file: A file-like object with a read() method.
        field_name: The form field name for the file.
        file_name: The filename to send.
        form_fields: Additional form fields to include.
        chunk_size: Size of chunks to read (default 64KB).

    Returns:
        Tuple of (generator, content_type_header).
    """
    boundary = _generate_boundary()
    content_type = f"multipart/form-data; boundary={boundary}"

    def _stream() -> Iterator[bytes]:
        if form_fields:
            for key, value in form_fields.items():
                yield f"--{boundary}\r\n".encode()
                yield f'Content-Disposition: form-data; name="{key}"\r\n\r\n'.encode()
                yield f"{value}\r\n".encode()

        yield f"--{boundary}\r\n".encode()
        yield f'Content-Disposition: form-data; name="{field_name}"; filename="{file_name}"\r\n'.encode()
        yield b"Content-Type: application/octet-stream\r\n\r\n"

        while True:
            chunk = file.read(chunk_size)
            if not chunk:
                break
            yield chunk

        yield f"\r\n--{boundary}--\r\n".encode()

    return _stream(), content_type


async def create_async_multipart_stream(
    file: Any,
    field_name: str = "file",
    file_name: str = "file",
    form_fields: Optional[Dict[str, str]] = None,
    chunk_size: int = 65536,
) -> Tuple[AsyncIterator[bytes], str]:
    """Create an async streaming multipart body.

    Args:
        file: A file-like object with a read() method.
        field_name: The form field name for the file.
        file_name: The filename to send.
        form_fields: Additional form fields to include.
        chunk_size: Size of chunks to read (default 64KB).

    Returns:
        Tuple of (async_generator, content_type_header).
    """
    boundary = _generate_boundary()
    content_type = f"multipart/form-data; boundary={boundary}"

    async def _stream() -> AsyncIterator[bytes]:
        if form_fields:
            for key, value in form_fields.items():
                yield f"--{boundary}\r\n".encode()
                yield f'Content-Disposition: form-data; name="{key}"\r\n\r\n'.encode()
                yield f"{value}\r\n".encode()

        yield f"--{boundary}\r\n".encode()
        yield f'Content-Disposition: form-data; name="{field_name}"; filename="{file_name}"\r\n'.encode()
        yield b"Content-Type: application/octet-stream\r\n\r\n"

        while True:
            chunk = file.read(chunk_size)
            if not chunk:
                break
            yield chunk

        yield f"\r\n--{boundary}--\r\n".encode()

    return _stream(), content_type
