"""
meibel-ai-api API client.

Generated by Forge SDK Generator.
"""

from typing import Optional
from ._http import HttpClient, AsyncHttpClient
from .resources.agents import AgentsResource, AsyncAgentsResource
from .resources.artifact_schemas import ArtifactSchemasResource, AsyncArtifactSchemasResource
from .resources.confidence_scoring import ConfidenceScoringResource, AsyncConfidenceScoringResource
from .resources.content import ContentResource, AsyncContentResource
from .resources.data_elements import DataElementsResource, AsyncDataElementsResource
from .resources.datasources import DatasourcesResource, AsyncDatasourcesResource
from .resources.documents import DocumentsResource, AsyncDocumentsResource
from .resources.downloads import DownloadsResource, AsyncDownloadsResource
from .resources.metadata_model_catalog import MetadataModelCatalogResource, AsyncMetadataModelCatalogResource
from .resources.prompts import PromptsResource, AsyncPromptsResource
from .resources.sessions import SessionsResource, AsyncSessionsResource
from .resources.table_descriptions import TableDescriptionsResource, AsyncTableDescriptionsResource


class MeibelClient:
    """Synchronous client for meibel-ai-api API."""

    def __init__(
        self,
        base_url: str = "https://api.meibel.ai/v2",
        api_key: Optional[str] = None,
        timeout: float = 30.0,
    ):
        """
        Initialize the Meibel client.

        Args:
            base_url: The API base URL
            api_key: API key for authentication
            timeout: Request timeout in seconds
        """
        self._http = HttpClient(base_url, api_key, timeout)

        self.agents = AgentsResource(self._http)
        self.artifact_schemas = ArtifactSchemasResource(self._http)
        self.confidence_scoring = ConfidenceScoringResource(self._http)
        self.content = ContentResource(self._http)
        self.data_elements = DataElementsResource(self._http)
        self.datasources = DatasourcesResource(self._http)
        self.documents = DocumentsResource(self._http)
        self.downloads = DownloadsResource(self._http)
        self.metadata_model_catalog = MetadataModelCatalogResource(self._http)
        self.prompts = PromptsResource(self._http)
        self.sessions = SessionsResource(self._http)
        self.table_descriptions = TableDescriptionsResource(self._http)

    def close(self) -> None:
        """Close the HTTP client."""
        self._http.close()

    def __enter__(self) -> "MeibelClient":
        return self

    def __exit__(self, *args) -> None:
        self.close()


class AsyncMeibelClient:
    """Asynchronous client for meibel-ai-api API."""

    def __init__(
        self,
        base_url: str = "https://api.meibel.ai/v2",
        api_key: Optional[str] = None,
        timeout: float = 30.0,
    ):
        """
        Initialize the async Meibel client.

        Args:
            base_url: The API base URL
            api_key: API key for authentication
            timeout: Request timeout in seconds
        """
        self._http = AsyncHttpClient(base_url, api_key, timeout)

        self.agents = AsyncAgentsResource(self._http)
        self.artifact_schemas = AsyncArtifactSchemasResource(self._http)
        self.confidence_scoring = AsyncConfidenceScoringResource(self._http)
        self.content = AsyncContentResource(self._http)
        self.data_elements = AsyncDataElementsResource(self._http)
        self.datasources = AsyncDatasourcesResource(self._http)
        self.documents = AsyncDocumentsResource(self._http)
        self.downloads = AsyncDownloadsResource(self._http)
        self.metadata_model_catalog = AsyncMetadataModelCatalogResource(self._http)
        self.prompts = AsyncPromptsResource(self._http)
        self.sessions = AsyncSessionsResource(self._http)
        self.table_descriptions = AsyncTableDescriptionsResource(self._http)

    async def close(self) -> None:
        """Close the HTTP client."""
        await self._http.close()

    async def __aenter__(self) -> "AsyncMeibelClient":
        return self

    async def __aexit__(self, *args) -> None:
        await self.close()