"""
API exceptions.

Generated by Forge SDK Generator.
"""

from typing import Optional, Dict, Any


class ApiError(Exception):
    """Base exception for API errors."""

    def __init__(
        self,
        message: str,
        status_code: Optional[int] = None,
        response_body: Optional[Dict[str, Any]] = None,
    ):
        super().__init__(message)
        self.message = message
        self.status_code = status_code
        self.response_body = response_body

    def __str__(self) -> str:
        if self.status_code:
            return f"[{self.status_code}] {self.message}"
        return self.message


class AuthenticationError(ApiError):
    """Raised when authentication fails (401)."""
    pass


class AuthorizationError(ApiError):
    """Raised when authorization fails (403)."""
    pass


class NotFoundError(ApiError):
    """Raised when a resource is not found (404)."""
    pass


class ValidationError(ApiError):
    """Raised when request validation fails (400, 422)."""
    pass


class RateLimitError(ApiError):
    """Raised when rate limit is exceeded (429)."""

    def __init__(
        self,
        message: str,
        retry_after: Optional[int] = None,
        **kwargs: Any,
    ):
        super().__init__(message, **kwargs)
        self.retry_after = retry_after


class ServerError(ApiError):
    """Raised when server error occurs (5xx)."""
    pass


def raise_for_status(status_code: int, message: str, body: Optional[Dict[str, Any]] = None) -> None:
    """Raise appropriate exception based on status code."""
    if status_code == 401:
        raise AuthenticationError(message, status_code, body)
    elif status_code == 403:
        raise AuthorizationError(message, status_code, body)
    elif status_code == 404:
        raise NotFoundError(message, status_code, body)
    elif status_code == 429:
        retry_after = None
        if body and "retry_after" in body:
            retry_after = body["retry_after"]
        raise RateLimitError(message, retry_after, status_code=status_code, response_body=body)
    elif status_code in (400, 422):
        raise ValidationError(message, status_code, body)
    elif status_code >= 500:
        raise ServerError(message, status_code, body)
    elif status_code >= 400:
        raise ApiError(message, status_code, body)
